/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.records.AppUserHistoryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserHistory extends TableImpl<AppUserHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_user_history</code>
     */
    public static final AppUserHistory APP_USER_HISTORY = new AppUserHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserHistoryRecord> getRecordType() {
        return AppUserHistoryRecord.class;
    }

    /**
     * The column <code>public.app_user_history.id</code>.
     */
    public final TableField<AppUserHistoryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.app_user_history.username</code>.
     */
    public final TableField<AppUserHistoryRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.app_user_history.email</code>.
     */
    public final TableField<AppUserHistoryRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.app_user_history.password_hash</code>.
     */
    public final TableField<AppUserHistoryRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.app_user_history.first_name</code>.
     */
    public final TableField<AppUserHistoryRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.app_user_history.last_name</code>.
     */
    public final TableField<AppUserHistoryRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.app_user_history.role</code>.
     */
    public final TableField<AppUserHistoryRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.app_user_history.enabled</code>.
     */
    public final TableField<AppUserHistoryRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.app_user_history.created_date</code>.
     */
    public final TableField<AppUserHistoryRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.app_user_history.created_by</code>.
     */
    public final TableField<AppUserHistoryRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.app_user_history.last_modified_date</code>.
     */
    public final TableField<AppUserHistoryRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.app_user_history.last_modified_by</code>.
     */
    public final TableField<AppUserHistoryRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.app_user_history.version</code>.
     */
    public final TableField<AppUserHistoryRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.app_user_history.dml_type</code>.
     */
    public final TableField<AppUserHistoryRecord, String> DML_TYPE = createField(DSL.name("dml_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.app_user_history.history_created_date</code>.
     */
    public final TableField<AppUserHistoryRecord, OffsetDateTime> HISTORY_CREATED_DATE = createField(DSL.name("history_created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AppUserHistory(Name alias, Table<AppUserHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppUserHistory(Name alias, Table<AppUserHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_user_history</code> table reference
     */
    public AppUserHistory(String alias) {
        this(DSL.name(alias), APP_USER_HISTORY);
    }

    /**
     * Create an aliased <code>public.app_user_history</code> table reference
     */
    public AppUserHistory(Name alias) {
        this(alias, APP_USER_HISTORY);
    }

    /**
     * Create a <code>public.app_user_history</code> table reference
     */
    public AppUserHistory() {
        this(DSL.name("app_user_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_APP_USER_HISTORY_CREATED_DATE, Indexes.IDX_APP_USER_HISTORY_ID);
    }

    @Override
    public AppUserHistory as(String alias) {
        return new AppUserHistory(DSL.name(alias), this);
    }

    @Override
    public AppUserHistory as(Name alias) {
        return new AppUserHistory(alias, this);
    }

    @Override
    public AppUserHistory as(Table<?> alias) {
        return new AppUserHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserHistory rename(String name) {
        return new AppUserHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserHistory rename(Name name) {
        return new AppUserHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserHistory rename(Table<?> name) {
        return new AppUserHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserHistory where(Condition condition) {
        return new AppUserHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
