/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Keys;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.Clinic.ClinicPath;
import com.lifelinecalllog.jooq.tables.ClinicLocationEmail.ClinicLocationEmailPath;
import com.lifelinecalllog.jooq.tables.DoctorClinic.DoctorClinicPath;
import com.lifelinecalllog.jooq.tables.PatientClinic.PatientClinicPath;
import com.lifelinecalllog.jooq.tables.Request.RequestPath;
import com.lifelinecalllog.jooq.tables.records.ClinicLocationRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicLocation extends TableImpl<ClinicLocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clinic_location</code>
     */
    public static final ClinicLocation CLINIC_LOCATION = new ClinicLocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClinicLocationRecord> getRecordType() {
        return ClinicLocationRecord.class;
    }

    /**
     * The column <code>public.clinic_location.id</code>.
     */
    public final TableField<ClinicLocationRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clinic_location.clinic_id</code>.
     */
    public final TableField<ClinicLocationRecord, UUID> CLINIC_ID = createField(DSL.name("clinic_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clinic_location.name</code>.
     */
    public final TableField<ClinicLocationRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.clinic_location.address_line1</code>.
     */
    public final TableField<ClinicLocationRecord, String> ADDRESS_LINE1 = createField(DSL.name("address_line1"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.clinic_location.address_line2</code>.
     */
    public final TableField<ClinicLocationRecord, String> ADDRESS_LINE2 = createField(DSL.name("address_line2"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.clinic_location.suburb</code>.
     */
    public final TableField<ClinicLocationRecord, String> SUBURB = createField(DSL.name("suburb"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.clinic_location.state</code>.
     */
    public final TableField<ClinicLocationRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'VIC'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.clinic_location.postcode</code>.
     */
    public final TableField<ClinicLocationRecord, String> POSTCODE = createField(DSL.name("postcode"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.clinic_location.latitude</code>.
     */
    public final TableField<ClinicLocationRecord, BigDecimal> LATITUDE = createField(DSL.name("latitude"), SQLDataType.NUMERIC(9, 6), this, "");

    /**
     * The column <code>public.clinic_location.longitude</code>.
     */
    public final TableField<ClinicLocationRecord, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.NUMERIC(9, 6), this, "");

    /**
     * The column <code>public.clinic_location.place_id</code>.
     */
    public final TableField<ClinicLocationRecord, String> PLACE_ID = createField(DSL.name("place_id"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.clinic_location.formatted_address</code>.
     */
    public final TableField<ClinicLocationRecord, String> FORMATTED_ADDRESS = createField(DSL.name("formatted_address"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.clinic_location.manager_name</code>.
     */
    public final TableField<ClinicLocationRecord, String> MANAGER_NAME = createField(DSL.name("manager_name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.clinic_location.care_coordination_name</code>.
     */
    public final TableField<ClinicLocationRecord, String> CARE_COORDINATION_NAME = createField(DSL.name("care_coordination_name"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>public.clinic_location.phone</code>.
     */
    public final TableField<ClinicLocationRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.clinic_location.fax</code>.
     */
    public final TableField<ClinicLocationRecord, String> FAX = createField(DSL.name("fax"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.clinic_location.is_primary</code>.
     */
    public final TableField<ClinicLocationRecord, Boolean> IS_PRIMARY = createField(DSL.name("is_primary"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.clinic_location.active</code>.
     */
    public final TableField<ClinicLocationRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.clinic_location.created_date</code>.
     */
    public final TableField<ClinicLocationRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.clinic_location.created_by</code>.
     */
    public final TableField<ClinicLocationRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100).nullable(false).defaultValue(DSL.field(DSL.raw("'system'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.clinic_location.last_modified_date</code>.
     */
    public final TableField<ClinicLocationRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.clinic_location.last_modified_by</code>.
     */
    public final TableField<ClinicLocationRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(100).nullable(false).defaultValue(DSL.field(DSL.raw("'system'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.clinic_location.version</code>.
     */
    public final TableField<ClinicLocationRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private ClinicLocation(Name alias, Table<ClinicLocationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClinicLocation(Name alias, Table<ClinicLocationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clinic_location</code> table reference
     */
    public ClinicLocation(String alias) {
        this(DSL.name(alias), CLINIC_LOCATION);
    }

    /**
     * Create an aliased <code>public.clinic_location</code> table reference
     */
    public ClinicLocation(Name alias) {
        this(alias, CLINIC_LOCATION);
    }

    /**
     * Create a <code>public.clinic_location</code> table reference
     */
    public ClinicLocation() {
        this(DSL.name("clinic_location"), null);
    }

    public <O extends Record> ClinicLocation(Table<O> path, ForeignKey<O, ClinicLocationRecord> childPath, InverseForeignKey<O, ClinicLocationRecord> parentPath) {
        super(path, childPath, parentPath, CLINIC_LOCATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClinicLocationPath extends ClinicLocation implements Path<ClinicLocationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClinicLocationPath(Table<O> path, ForeignKey<O, ClinicLocationRecord> childPath, InverseForeignKey<O, ClinicLocationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClinicLocationPath(Name alias, Table<ClinicLocationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClinicLocationPath as(String alias) {
            return new ClinicLocationPath(DSL.name(alias), this);
        }

        @Override
        public ClinicLocationPath as(Name alias) {
            return new ClinicLocationPath(alias, this);
        }

        @Override
        public ClinicLocationPath as(Table<?> alias) {
            return new ClinicLocationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLINIC_LOCATION_ACTIVE, Indexes.IDX_CLINIC_LOCATION_CLINIC_ID, Indexes.IDX_CLINIC_LOCATION_IS_PRIMARY, Indexes.IDX_CLINIC_LOCATION_SUBURB);
    }

    @Override
    public UniqueKey<ClinicLocationRecord> getPrimaryKey() {
        return Keys.CLINIC_LOCATION_PKEY;
    }

    @Override
    public List<ForeignKey<ClinicLocationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLINIC_LOCATION__FK_CLINIC_LOCATION_CLINIC);
    }

    private transient ClinicPath _clinic;

    /**
     * Get the implicit join path to the <code>public.clinic</code> table.
     */
    public ClinicPath clinic() {
        if (_clinic == null)
            _clinic = new ClinicPath(this, Keys.CLINIC_LOCATION__FK_CLINIC_LOCATION_CLINIC, null);

        return _clinic;
    }

    private transient ClinicLocationEmailPath _clinicLocationEmail;

    /**
     * Get the implicit to-many join path to the
     * <code>public.clinic_location_email</code> table
     */
    public ClinicLocationEmailPath clinicLocationEmail() {
        if (_clinicLocationEmail == null)
            _clinicLocationEmail = new ClinicLocationEmailPath(this, null, Keys.CLINIC_LOCATION_EMAIL__FK_CLINIC_LOCATION_EMAIL_LOCATION.getInverseKey());

        return _clinicLocationEmail;
    }

    private transient DoctorClinicPath _doctorClinic;

    /**
     * Get the implicit to-many join path to the
     * <code>public.doctor_clinic</code> table
     */
    public DoctorClinicPath doctorClinic() {
        if (_doctorClinic == null)
            _doctorClinic = new DoctorClinicPath(this, null, Keys.DOCTOR_CLINIC__FK_DOCTOR_CLINIC_LOCATION.getInverseKey());

        return _doctorClinic;
    }

    private transient PatientClinicPath _patientClinic;

    /**
     * Get the implicit to-many join path to the
     * <code>public.patient_clinic</code> table
     */
    public PatientClinicPath patientClinic() {
        if (_patientClinic == null)
            _patientClinic = new PatientClinicPath(this, null, Keys.PATIENT_CLINIC__FK_PATIENT_CLINIC_LOCATION.getInverseKey());

        return _patientClinic;
    }

    private transient RequestPath _request;

    /**
     * Get the implicit to-many join path to the <code>public.request</code>
     * table
     */
    public RequestPath request() {
        if (_request == null)
            _request = new RequestPath(this, null, Keys.REQUEST__FK_REQUEST_CLINIC_LOCATION.getInverseKey());

        return _request;
    }

    @Override
    public ClinicLocation as(String alias) {
        return new ClinicLocation(DSL.name(alias), this);
    }

    @Override
    public ClinicLocation as(Name alias) {
        return new ClinicLocation(alias, this);
    }

    @Override
    public ClinicLocation as(Table<?> alias) {
        return new ClinicLocation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClinicLocation rename(String name) {
        return new ClinicLocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClinicLocation rename(Name name) {
        return new ClinicLocation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClinicLocation rename(Table<?> name) {
        return new ClinicLocation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocation where(Condition condition) {
        return new ClinicLocation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
