/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Keys;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.ClinicLocation.ClinicLocationPath;
import com.lifelinecalllog.jooq.tables.records.ClinicLocationEmailRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicLocationEmail extends TableImpl<ClinicLocationEmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clinic_location_email</code>
     */
    public static final ClinicLocationEmail CLINIC_LOCATION_EMAIL = new ClinicLocationEmail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClinicLocationEmailRecord> getRecordType() {
        return ClinicLocationEmailRecord.class;
    }

    /**
     * The column <code>public.clinic_location_email.id</code>.
     */
    public final TableField<ClinicLocationEmailRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clinic_location_email.clinic_location_id</code>.
     */
    public final TableField<ClinicLocationEmailRecord, UUID> CLINIC_LOCATION_ID = createField(DSL.name("clinic_location_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clinic_location_email.email</code>.
     */
    public final TableField<ClinicLocationEmailRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.clinic_location_email.label</code>.
     */
    public final TableField<ClinicLocationEmailRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.clinic_location_email.is_primary</code>.
     */
    public final TableField<ClinicLocationEmailRecord, Boolean> IS_PRIMARY = createField(DSL.name("is_primary"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.clinic_location_email.created_date</code>.
     */
    public final TableField<ClinicLocationEmailRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.clinic_location_email.created_by</code>.
     */
    public final TableField<ClinicLocationEmailRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100).nullable(false).defaultValue(DSL.field(DSL.raw("'system'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.clinic_location_email.last_modified_date</code>.
     */
    public final TableField<ClinicLocationEmailRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.clinic_location_email.last_modified_by</code>.
     */
    public final TableField<ClinicLocationEmailRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(100).nullable(false).defaultValue(DSL.field(DSL.raw("'system'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.clinic_location_email.version</code>.
     */
    public final TableField<ClinicLocationEmailRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private ClinicLocationEmail(Name alias, Table<ClinicLocationEmailRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClinicLocationEmail(Name alias, Table<ClinicLocationEmailRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clinic_location_email</code> table
     * reference
     */
    public ClinicLocationEmail(String alias) {
        this(DSL.name(alias), CLINIC_LOCATION_EMAIL);
    }

    /**
     * Create an aliased <code>public.clinic_location_email</code> table
     * reference
     */
    public ClinicLocationEmail(Name alias) {
        this(alias, CLINIC_LOCATION_EMAIL);
    }

    /**
     * Create a <code>public.clinic_location_email</code> table reference
     */
    public ClinicLocationEmail() {
        this(DSL.name("clinic_location_email"), null);
    }

    public <O extends Record> ClinicLocationEmail(Table<O> path, ForeignKey<O, ClinicLocationEmailRecord> childPath, InverseForeignKey<O, ClinicLocationEmailRecord> parentPath) {
        super(path, childPath, parentPath, CLINIC_LOCATION_EMAIL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClinicLocationEmailPath extends ClinicLocationEmail implements Path<ClinicLocationEmailRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClinicLocationEmailPath(Table<O> path, ForeignKey<O, ClinicLocationEmailRecord> childPath, InverseForeignKey<O, ClinicLocationEmailRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClinicLocationEmailPath(Name alias, Table<ClinicLocationEmailRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClinicLocationEmailPath as(String alias) {
            return new ClinicLocationEmailPath(DSL.name(alias), this);
        }

        @Override
        public ClinicLocationEmailPath as(Name alias) {
            return new ClinicLocationEmailPath(alias, this);
        }

        @Override
        public ClinicLocationEmailPath as(Table<?> alias) {
            return new ClinicLocationEmailPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLINIC_LOCATION_EMAIL_LOCATION_ID);
    }

    @Override
    public UniqueKey<ClinicLocationEmailRecord> getPrimaryKey() {
        return Keys.CLINIC_LOCATION_EMAIL_PKEY;
    }

    @Override
    public List<ForeignKey<ClinicLocationEmailRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLINIC_LOCATION_EMAIL__FK_CLINIC_LOCATION_EMAIL_LOCATION);
    }

    private transient ClinicLocationPath _clinicLocation;

    /**
     * Get the implicit join path to the <code>public.clinic_location</code>
     * table.
     */
    public ClinicLocationPath clinicLocation() {
        if (_clinicLocation == null)
            _clinicLocation = new ClinicLocationPath(this, Keys.CLINIC_LOCATION_EMAIL__FK_CLINIC_LOCATION_EMAIL_LOCATION, null);

        return _clinicLocation;
    }

    @Override
    public ClinicLocationEmail as(String alias) {
        return new ClinicLocationEmail(DSL.name(alias), this);
    }

    @Override
    public ClinicLocationEmail as(Name alias) {
        return new ClinicLocationEmail(alias, this);
    }

    @Override
    public ClinicLocationEmail as(Table<?> alias) {
        return new ClinicLocationEmail(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClinicLocationEmail rename(String name) {
        return new ClinicLocationEmail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClinicLocationEmail rename(Name name) {
        return new ClinicLocationEmail(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClinicLocationEmail rename(Table<?> name) {
        return new ClinicLocationEmail(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocationEmail where(Condition condition) {
        return new ClinicLocationEmail(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocationEmail where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocationEmail where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocationEmail where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocationEmail where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocationEmail where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocationEmail where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClinicLocationEmail where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocationEmail whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClinicLocationEmail whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
