/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.records.ConfigurationHistoryRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConfigurationHistory extends TableImpl<ConfigurationHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.configuration_history</code>
     */
    public static final ConfigurationHistory CONFIGURATION_HISTORY = new ConfigurationHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConfigurationHistoryRecord> getRecordType() {
        return ConfigurationHistoryRecord.class;
    }

    /**
     * The column <code>public.configuration_history.config_group</code>.
     */
    public final TableField<ConfigurationHistoryRecord, String> CONFIG_GROUP = createField(DSL.name("config_group"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.configuration_history.group_display_order</code>.
     */
    public final TableField<ConfigurationHistoryRecord, Integer> GROUP_DISPLAY_ORDER = createField(DSL.name("group_display_order"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.configuration_history.config_key</code>.
     */
    public final TableField<ConfigurationHistoryRecord, String> CONFIG_KEY = createField(DSL.name("config_key"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.configuration_history.config_description</code>.
     */
    public final TableField<ConfigurationHistoryRecord, String> CONFIG_DESCRIPTION = createField(DSL.name("config_description"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column
     * <code>public.configuration_history.config_display_order</code>.
     */
    public final TableField<ConfigurationHistoryRecord, Integer> CONFIG_DISPLAY_ORDER = createField(DSL.name("config_display_order"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.configuration_history.status</code>.
     */
    public final TableField<ConfigurationHistoryRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.configuration_history.created_date</code>.
     */
    public final TableField<ConfigurationHistoryRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.configuration_history.created_by</code>.
     */
    public final TableField<ConfigurationHistoryRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.configuration_history.last_modified_date</code>.
     */
    public final TableField<ConfigurationHistoryRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.configuration_history.last_modified_by</code>.
     */
    public final TableField<ConfigurationHistoryRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.configuration_history.version</code>.
     */
    public final TableField<ConfigurationHistoryRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.configuration_history.dml_type</code>.
     */
    public final TableField<ConfigurationHistoryRecord, String> DML_TYPE = createField(DSL.name("dml_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column
     * <code>public.configuration_history.history_created_date</code>.
     */
    public final TableField<ConfigurationHistoryRecord, OffsetDateTime> HISTORY_CREATED_DATE = createField(DSL.name("history_created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ConfigurationHistory(Name alias, Table<ConfigurationHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ConfigurationHistory(Name alias, Table<ConfigurationHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.configuration_history</code> table
     * reference
     */
    public ConfigurationHistory(String alias) {
        this(DSL.name(alias), CONFIGURATION_HISTORY);
    }

    /**
     * Create an aliased <code>public.configuration_history</code> table
     * reference
     */
    public ConfigurationHistory(Name alias) {
        this(alias, CONFIGURATION_HISTORY);
    }

    /**
     * Create a <code>public.configuration_history</code> table reference
     */
    public ConfigurationHistory() {
        this(DSL.name("configuration_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public ConfigurationHistory as(String alias) {
        return new ConfigurationHistory(DSL.name(alias), this);
    }

    @Override
    public ConfigurationHistory as(Name alias) {
        return new ConfigurationHistory(alias, this);
    }

    @Override
    public ConfigurationHistory as(Table<?> alias) {
        return new ConfigurationHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConfigurationHistory rename(String name) {
        return new ConfigurationHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConfigurationHistory rename(Name name) {
        return new ConfigurationHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConfigurationHistory rename(Table<?> name) {
        return new ConfigurationHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConfigurationHistory where(Condition condition) {
        return new ConfigurationHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConfigurationHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConfigurationHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConfigurationHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConfigurationHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConfigurationHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConfigurationHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConfigurationHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConfigurationHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConfigurationHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
