/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.records.DoctorClinicHistoryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DoctorClinicHistory extends TableImpl<DoctorClinicHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.doctor_clinic_history</code>
     */
    public static final DoctorClinicHistory DOCTOR_CLINIC_HISTORY = new DoctorClinicHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoctorClinicHistoryRecord> getRecordType() {
        return DoctorClinicHistoryRecord.class;
    }

    /**
     * The column <code>public.doctor_clinic_history.id</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor_clinic_history.doctor_id</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, UUID> DOCTOR_ID = createField(DSL.name("doctor_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor_clinic_history.clinic_id</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, UUID> CLINIC_ID = createField(DSL.name("clinic_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor_clinic_history.clinic_location_id</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, UUID> CLINIC_LOCATION_ID = createField(DSL.name("clinic_location_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor_clinic_history.active</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.doctor_clinic_history.created_date</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.doctor_clinic_history.created_by</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor_clinic_history.last_modified_date</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.doctor_clinic_history.last_modified_by</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor_clinic_history.version</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.doctor_clinic_history.dml_type</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, String> DML_TYPE = createField(DSL.name("dml_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column
     * <code>public.doctor_clinic_history.history_created_date</code>.
     */
    public final TableField<DoctorClinicHistoryRecord, OffsetDateTime> HISTORY_CREATED_DATE = createField(DSL.name("history_created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private DoctorClinicHistory(Name alias, Table<DoctorClinicHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DoctorClinicHistory(Name alias, Table<DoctorClinicHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.doctor_clinic_history</code> table
     * reference
     */
    public DoctorClinicHistory(String alias) {
        this(DSL.name(alias), DOCTOR_CLINIC_HISTORY);
    }

    /**
     * Create an aliased <code>public.doctor_clinic_history</code> table
     * reference
     */
    public DoctorClinicHistory(Name alias) {
        this(alias, DOCTOR_CLINIC_HISTORY);
    }

    /**
     * Create a <code>public.doctor_clinic_history</code> table reference
     */
    public DoctorClinicHistory() {
        this(DSL.name("doctor_clinic_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DOCTOR_CLINIC_HISTORY_ID);
    }

    @Override
    public DoctorClinicHistory as(String alias) {
        return new DoctorClinicHistory(DSL.name(alias), this);
    }

    @Override
    public DoctorClinicHistory as(Name alias) {
        return new DoctorClinicHistory(alias, this);
    }

    @Override
    public DoctorClinicHistory as(Table<?> alias) {
        return new DoctorClinicHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DoctorClinicHistory rename(String name) {
        return new DoctorClinicHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DoctorClinicHistory rename(Name name) {
        return new DoctorClinicHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DoctorClinicHistory rename(Table<?> name) {
        return new DoctorClinicHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoctorClinicHistory where(Condition condition) {
        return new DoctorClinicHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoctorClinicHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoctorClinicHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoctorClinicHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoctorClinicHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoctorClinicHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoctorClinicHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoctorClinicHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoctorClinicHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoctorClinicHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
