/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Keys;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.Request.RequestPath;
import com.lifelinecalllog.jooq.tables.records.DoctorRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Doctor extends TableImpl<DoctorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.doctor</code>
     */
    public static final Doctor DOCTOR = new Doctor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoctorRecord> getRecordType() {
        return DoctorRecord.class;
    }

    /**
     * The column <code>public.doctor.id</code>.
     */
    public final TableField<DoctorRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.doctor.first_name</code>.
     */
    public final TableField<DoctorRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.doctor.last_name</code>.
     */
    public final TableField<DoctorRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.doctor.provider_number</code>.
     */
    public final TableField<DoctorRecord, String> PROVIDER_NUMBER = createField(DSL.name("provider_number"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.doctor.phone</code>.
     */
    public final TableField<DoctorRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.doctor.email</code>.
     */
    public final TableField<DoctorRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.doctor.active</code>.
     */
    public final TableField<DoctorRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.doctor.created_date</code>.
     */
    public final TableField<DoctorRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.doctor.created_by</code>.
     */
    public final TableField<DoctorRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor.last_modified_date</code>.
     */
    public final TableField<DoctorRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.doctor.last_modified_by</code>.
     */
    public final TableField<DoctorRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.doctor.version</code>.
     */
    public final TableField<DoctorRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private Doctor(Name alias, Table<DoctorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Doctor(Name alias, Table<DoctorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.doctor</code> table reference
     */
    public Doctor(String alias) {
        this(DSL.name(alias), DOCTOR);
    }

    /**
     * Create an aliased <code>public.doctor</code> table reference
     */
    public Doctor(Name alias) {
        this(alias, DOCTOR);
    }

    /**
     * Create a <code>public.doctor</code> table reference
     */
    public Doctor() {
        this(DSL.name("doctor"), null);
    }

    public <O extends Record> Doctor(Table<O> path, ForeignKey<O, DoctorRecord> childPath, InverseForeignKey<O, DoctorRecord> parentPath) {
        super(path, childPath, parentPath, DOCTOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DoctorPath extends Doctor implements Path<DoctorRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DoctorPath(Table<O> path, ForeignKey<O, DoctorRecord> childPath, InverseForeignKey<O, DoctorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DoctorPath(Name alias, Table<DoctorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DoctorPath as(String alias) {
            return new DoctorPath(DSL.name(alias), this);
        }

        @Override
        public DoctorPath as(Name alias) {
            return new DoctorPath(alias, this);
        }

        @Override
        public DoctorPath as(Table<?> alias) {
            return new DoctorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DOCTOR_ACTIVE, Indexes.IDX_DOCTOR_LAST_NAME);
    }

    @Override
    public UniqueKey<DoctorRecord> getPrimaryKey() {
        return Keys.DOCTOR_PKEY;
    }

    private transient RequestPath _request;

    /**
     * Get the implicit to-many join path to the <code>public.request</code>
     * table
     */
    public RequestPath request() {
        if (_request == null)
            _request = new RequestPath(this, null, Keys.REQUEST__FK_REQUEST_DOCTOR.getInverseKey());

        return _request;
    }

    @Override
    public Doctor as(String alias) {
        return new Doctor(DSL.name(alias), this);
    }

    @Override
    public Doctor as(Name alias) {
        return new Doctor(alias, this);
    }

    @Override
    public Doctor as(Table<?> alias) {
        return new Doctor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctor rename(String name) {
        return new Doctor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctor rename(Name name) {
        return new Doctor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Doctor rename(Table<?> name) {
        return new Doctor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Doctor where(Condition condition) {
        return new Doctor(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Doctor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Doctor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Doctor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Doctor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Doctor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Doctor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Doctor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Doctor whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Doctor whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
