/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Keys;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.AppUser.AppUserPath;
import com.lifelinecalllog.jooq.tables.records.PasswordResetTokenRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordResetToken extends TableImpl<PasswordResetTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.password_reset_token</code>
     */
    public static final PasswordResetToken PASSWORD_RESET_TOKEN = new PasswordResetToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PasswordResetTokenRecord> getRecordType() {
        return PasswordResetTokenRecord.class;
    }

    /**
     * The column <code>public.password_reset_token.token</code>.
     */
    public final TableField<PasswordResetTokenRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.password_reset_token.user_id</code>.
     */
    public final TableField<PasswordResetTokenRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.password_reset_token.expires_at</code>.
     */
    public final TableField<PasswordResetTokenRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.password_reset_token.used</code>.
     */
    public final TableField<PasswordResetTokenRecord, Boolean> USED = createField(DSL.name("used"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.password_reset_token.created_at</code>.
     */
    public final TableField<PasswordResetTokenRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private PasswordResetToken(Name alias, Table<PasswordResetTokenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PasswordResetToken(Name alias, Table<PasswordResetTokenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.password_reset_token</code> table
     * reference
     */
    public PasswordResetToken(String alias) {
        this(DSL.name(alias), PASSWORD_RESET_TOKEN);
    }

    /**
     * Create an aliased <code>public.password_reset_token</code> table
     * reference
     */
    public PasswordResetToken(Name alias) {
        this(alias, PASSWORD_RESET_TOKEN);
    }

    /**
     * Create a <code>public.password_reset_token</code> table reference
     */
    public PasswordResetToken() {
        this(DSL.name("password_reset_token"), null);
    }

    public <O extends Record> PasswordResetToken(Table<O> path, ForeignKey<O, PasswordResetTokenRecord> childPath, InverseForeignKey<O, PasswordResetTokenRecord> parentPath) {
        super(path, childPath, parentPath, PASSWORD_RESET_TOKEN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PasswordResetTokenPath extends PasswordResetToken implements Path<PasswordResetTokenRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PasswordResetTokenPath(Table<O> path, ForeignKey<O, PasswordResetTokenRecord> childPath, InverseForeignKey<O, PasswordResetTokenRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PasswordResetTokenPath(Name alias, Table<PasswordResetTokenRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PasswordResetTokenPath as(String alias) {
            return new PasswordResetTokenPath(DSL.name(alias), this);
        }

        @Override
        public PasswordResetTokenPath as(Name alias) {
            return new PasswordResetTokenPath(alias, this);
        }

        @Override
        public PasswordResetTokenPath as(Table<?> alias) {
            return new PasswordResetTokenPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PASSWORD_RESET_TOKEN_USER_ID);
    }

    @Override
    public UniqueKey<PasswordResetTokenRecord> getPrimaryKey() {
        return Keys.PASSWORD_RESET_TOKEN_PKEY;
    }

    @Override
    public List<ForeignKey<PasswordResetTokenRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PASSWORD_RESET_TOKEN__PASSWORD_RESET_TOKEN_USER_ID_FKEY);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.PASSWORD_RESET_TOKEN__PASSWORD_RESET_TOKEN_USER_ID_FKEY, null);

        return _appUser;
    }

    @Override
    public PasswordResetToken as(String alias) {
        return new PasswordResetToken(DSL.name(alias), this);
    }

    @Override
    public PasswordResetToken as(Name alias) {
        return new PasswordResetToken(alias, this);
    }

    @Override
    public PasswordResetToken as(Table<?> alias) {
        return new PasswordResetToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PasswordResetToken rename(String name) {
        return new PasswordResetToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PasswordResetToken rename(Name name) {
        return new PasswordResetToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PasswordResetToken rename(Table<?> name) {
        return new PasswordResetToken(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PasswordResetToken where(Condition condition) {
        return new PasswordResetToken(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PasswordResetToken where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PasswordResetToken where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PasswordResetToken where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PasswordResetToken where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PasswordResetToken where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PasswordResetToken where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PasswordResetToken where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PasswordResetToken whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PasswordResetToken whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
