/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Keys;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.PatientClinic.PatientClinicPath;
import com.lifelinecalllog.jooq.tables.Request.RequestPath;
import com.lifelinecalllog.jooq.tables.RequestPatient.RequestPatientPath;
import com.lifelinecalllog.jooq.tables.records.PatientRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Patient extends TableImpl<PatientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.patient</code>
     */
    public static final Patient PATIENT = new Patient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PatientRecord> getRecordType() {
        return PatientRecord.class;
    }

    /**
     * The column <code>public.patient.id</code>.
     */
    public final TableField<PatientRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.patient.first_name</code>.
     */
    public final TableField<PatientRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.patient.last_name</code>.
     */
    public final TableField<PatientRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.patient.date_of_birth</code>.
     */
    public final TableField<PatientRecord, LocalDate> DATE_OF_BIRTH = createField(DSL.name("date_of_birth"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.patient.phone</code>.
     */
    public final TableField<PatientRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.patient.active</code>.
     */
    public final TableField<PatientRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.patient.created_date</code>.
     */
    public final TableField<PatientRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.patient.created_by</code>.
     */
    public final TableField<PatientRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.patient.last_modified_date</code>.
     */
    public final TableField<PatientRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.patient.last_modified_by</code>.
     */
    public final TableField<PatientRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.patient.version</code>.
     */
    public final TableField<PatientRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private Patient(Name alias, Table<PatientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Patient(Name alias, Table<PatientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.patient</code> table reference
     */
    public Patient(String alias) {
        this(DSL.name(alias), PATIENT);
    }

    /**
     * Create an aliased <code>public.patient</code> table reference
     */
    public Patient(Name alias) {
        this(alias, PATIENT);
    }

    /**
     * Create a <code>public.patient</code> table reference
     */
    public Patient() {
        this(DSL.name("patient"), null);
    }

    public <O extends Record> Patient(Table<O> path, ForeignKey<O, PatientRecord> childPath, InverseForeignKey<O, PatientRecord> parentPath) {
        super(path, childPath, parentPath, PATIENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PatientPath extends Patient implements Path<PatientRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PatientPath(Table<O> path, ForeignKey<O, PatientRecord> childPath, InverseForeignKey<O, PatientRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PatientPath(Name alias, Table<PatientRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PatientPath as(String alias) {
            return new PatientPath(DSL.name(alias), this);
        }

        @Override
        public PatientPath as(Name alias) {
            return new PatientPath(alias, this);
        }

        @Override
        public PatientPath as(Table<?> alias) {
            return new PatientPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PATIENT_ACTIVE, Indexes.IDX_PATIENT_LAST_NAME);
    }

    @Override
    public UniqueKey<PatientRecord> getPrimaryKey() {
        return Keys.PATIENT_PKEY;
    }

    private transient PatientClinicPath _patientClinic;

    /**
     * Get the implicit to-many join path to the
     * <code>public.patient_clinic</code> table
     */
    public PatientClinicPath patientClinic() {
        if (_patientClinic == null)
            _patientClinic = new PatientClinicPath(this, null, Keys.PATIENT_CLINIC__FK_PATIENT_CLINIC_PATIENT.getInverseKey());

        return _patientClinic;
    }

    private transient RequestPatientPath _requestPatient;

    /**
     * Get the implicit to-many join path to the
     * <code>public.request_patient</code> table
     */
    public RequestPatientPath requestPatient() {
        if (_requestPatient == null)
            _requestPatient = new RequestPatientPath(this, null, Keys.REQUEST_PATIENT__FK_REQUEST_PATIENT_PATIENT.getInverseKey());

        return _requestPatient;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.request</code> table
     */
    public RequestPath request() {
        return requestPatient().request();
    }

    @Override
    public Patient as(String alias) {
        return new Patient(DSL.name(alias), this);
    }

    @Override
    public Patient as(Name alias) {
        return new Patient(alias, this);
    }

    @Override
    public Patient as(Table<?> alias) {
        return new Patient(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Patient rename(String name) {
        return new Patient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Patient rename(Name name) {
        return new Patient(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Patient rename(Table<?> name) {
        return new Patient(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Patient where(Condition condition) {
        return new Patient(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Patient where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Patient where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Patient where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Patient where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Patient where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Patient where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Patient where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Patient whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Patient whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
