/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.enums.PatientStatus;
import com.lifelinecalllog.jooq.tables.records.PatientHistoryRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientHistory extends TableImpl<PatientHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.patient_history</code>
     */
    public static final PatientHistory PATIENT_HISTORY = new PatientHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PatientHistoryRecord> getRecordType() {
        return PatientHistoryRecord.class;
    }

    /**
     * The column <code>public.patient_history.id</code>.
     */
    public final TableField<PatientHistoryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.patient_history.first_name</code>.
     */
    public final TableField<PatientHistoryRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.patient_history.last_name</code>.
     */
    public final TableField<PatientHistoryRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.patient_history.date_of_birth</code>.
     */
    public final TableField<PatientHistoryRecord, LocalDate> DATE_OF_BIRTH = createField(DSL.name("date_of_birth"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.patient_history.phone</code>.
     */
    public final TableField<PatientHistoryRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.patient_history.created_date</code>.
     */
    public final TableField<PatientHistoryRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.patient_history.created_by</code>.
     */
    public final TableField<PatientHistoryRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.patient_history.last_modified_date</code>.
     */
    public final TableField<PatientHistoryRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.patient_history.last_modified_by</code>.
     */
    public final TableField<PatientHistoryRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.patient_history.version</code>.
     */
    public final TableField<PatientHistoryRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.patient_history.dml_type</code>.
     */
    public final TableField<PatientHistoryRecord, String> DML_TYPE = createField(DSL.name("dml_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.patient_history.history_created_date</code>.
     */
    public final TableField<PatientHistoryRecord, OffsetDateTime> HISTORY_CREATED_DATE = createField(DSL.name("history_created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.patient_history.status</code>.
     */
    public final TableField<PatientHistoryRecord, PatientStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.asEnumDataType(PatientStatus.class), this, "");

    /**
     * The column <code>public.patient_history.status_reason</code>.
     */
    public final TableField<PatientHistoryRecord, String> STATUS_REASON = createField(DSL.name("status_reason"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.patient_history.deceased_date</code>.
     */
    public final TableField<PatientHistoryRecord, LocalDate> DECEASED_DATE = createField(DSL.name("deceased_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.patient_history.medicare_no</code>.
     */
    public final TableField<PatientHistoryRecord, String> MEDICARE_NO = createField(DSL.name("medicare_no"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.patient_history.irn_no</code>.
     */
    public final TableField<PatientHistoryRecord, String> IRN_NO = createField(DSL.name("irn_no"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.patient_history.remark</code>.
     */
    public final TableField<PatientHistoryRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.CLOB, this, "");

    private PatientHistory(Name alias, Table<PatientHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PatientHistory(Name alias, Table<PatientHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.patient_history</code> table reference
     */
    public PatientHistory(String alias) {
        this(DSL.name(alias), PATIENT_HISTORY);
    }

    /**
     * Create an aliased <code>public.patient_history</code> table reference
     */
    public PatientHistory(Name alias) {
        this(alias, PATIENT_HISTORY);
    }

    /**
     * Create a <code>public.patient_history</code> table reference
     */
    public PatientHistory() {
        this(DSL.name("patient_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PATIENT_HISTORY_CREATED_DATE, Indexes.IDX_PATIENT_HISTORY_ID);
    }

    @Override
    public PatientHistory as(String alias) {
        return new PatientHistory(DSL.name(alias), this);
    }

    @Override
    public PatientHistory as(Name alias) {
        return new PatientHistory(alias, this);
    }

    @Override
    public PatientHistory as(Table<?> alias) {
        return new PatientHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientHistory rename(String name) {
        return new PatientHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientHistory rename(Name name) {
        return new PatientHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientHistory rename(Table<?> name) {
        return new PatientHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PatientHistory where(Condition condition) {
        return new PatientHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PatientHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PatientHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PatientHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PatientHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PatientHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PatientHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PatientHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PatientHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PatientHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
