/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.records.RefreshTokenHistoryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokenHistory extends TableImpl<RefreshTokenHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.refresh_token_history</code>
     */
    public static final RefreshTokenHistory REFRESH_TOKEN_HISTORY = new RefreshTokenHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RefreshTokenHistoryRecord> getRecordType() {
        return RefreshTokenHistoryRecord.class;
    }

    /**
     * The column <code>public.refresh_token_history.id</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.refresh_token_history.token</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.refresh_token_history.user_id</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.refresh_token_history.expiry_date</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, OffsetDateTime> EXPIRY_DATE = createField(DSL.name("expiry_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.refresh_token_history.revoked</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, Boolean> REVOKED = createField(DSL.name("revoked"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.refresh_token_history.created_date</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.refresh_token_history.created_by</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.refresh_token_history.last_modified_date</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.refresh_token_history.last_modified_by</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.refresh_token_history.version</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.refresh_token_history.dml_type</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, String> DML_TYPE = createField(DSL.name("dml_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column
     * <code>public.refresh_token_history.history_created_date</code>.
     */
    public final TableField<RefreshTokenHistoryRecord, OffsetDateTime> HISTORY_CREATED_DATE = createField(DSL.name("history_created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private RefreshTokenHistory(Name alias, Table<RefreshTokenHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RefreshTokenHistory(Name alias, Table<RefreshTokenHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.refresh_token_history</code> table
     * reference
     */
    public RefreshTokenHistory(String alias) {
        this(DSL.name(alias), REFRESH_TOKEN_HISTORY);
    }

    /**
     * Create an aliased <code>public.refresh_token_history</code> table
     * reference
     */
    public RefreshTokenHistory(Name alias) {
        this(alias, REFRESH_TOKEN_HISTORY);
    }

    /**
     * Create a <code>public.refresh_token_history</code> table reference
     */
    public RefreshTokenHistory() {
        this(DSL.name("refresh_token_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REFRESH_TOKEN_HISTORY_CREATED_DATE, Indexes.IDX_REFRESH_TOKEN_HISTORY_ID);
    }

    @Override
    public RefreshTokenHistory as(String alias) {
        return new RefreshTokenHistory(DSL.name(alias), this);
    }

    @Override
    public RefreshTokenHistory as(Name alias) {
        return new RefreshTokenHistory(alias, this);
    }

    @Override
    public RefreshTokenHistory as(Table<?> alias) {
        return new RefreshTokenHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokenHistory rename(String name) {
        return new RefreshTokenHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokenHistory rename(Name name) {
        return new RefreshTokenHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokenHistory rename(Table<?> name) {
        return new RefreshTokenHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokenHistory where(Condition condition) {
        return new RefreshTokenHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokenHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokenHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokenHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokenHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokenHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokenHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokenHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokenHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokenHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
