/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables;


import com.lifelinecalllog.jooq.Indexes;
import com.lifelinecalllog.jooq.Keys;
import com.lifelinecalllog.jooq.Public;
import com.lifelinecalllog.jooq.tables.Patient.PatientPath;
import com.lifelinecalllog.jooq.tables.Request.RequestPath;
import com.lifelinecalllog.jooq.tables.records.RequestPatientRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RequestPatient extends TableImpl<RequestPatientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.request_patient</code>
     */
    public static final RequestPatient REQUEST_PATIENT = new RequestPatient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RequestPatientRecord> getRecordType() {
        return RequestPatientRecord.class;
    }

    /**
     * The column <code>public.request_patient.id</code>.
     */
    public final TableField<RequestPatientRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.request_patient.request_id</code>.
     */
    public final TableField<RequestPatientRecord, UUID> REQUEST_ID = createField(DSL.name("request_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.request_patient.patient_id</code>.
     */
    public final TableField<RequestPatientRecord, UUID> PATIENT_ID = createField(DSL.name("patient_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.request_patient.notes</code>.
     */
    public final TableField<RequestPatientRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.request_patient.created_date</code>.
     */
    public final TableField<RequestPatientRecord, OffsetDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.request_patient.created_by</code>.
     */
    public final TableField<RequestPatientRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.request_patient.last_modified_date</code>.
     */
    public final TableField<RequestPatientRecord, OffsetDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.request_patient.last_modified_by</code>.
     */
    public final TableField<RequestPatientRecord, UUID> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.request_patient.version</code>.
     */
    public final TableField<RequestPatientRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private RequestPatient(Name alias, Table<RequestPatientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RequestPatient(Name alias, Table<RequestPatientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.request_patient</code> table reference
     */
    public RequestPatient(String alias) {
        this(DSL.name(alias), REQUEST_PATIENT);
    }

    /**
     * Create an aliased <code>public.request_patient</code> table reference
     */
    public RequestPatient(Name alias) {
        this(alias, REQUEST_PATIENT);
    }

    /**
     * Create a <code>public.request_patient</code> table reference
     */
    public RequestPatient() {
        this(DSL.name("request_patient"), null);
    }

    public <O extends Record> RequestPatient(Table<O> path, ForeignKey<O, RequestPatientRecord> childPath, InverseForeignKey<O, RequestPatientRecord> parentPath) {
        super(path, childPath, parentPath, REQUEST_PATIENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RequestPatientPath extends RequestPatient implements Path<RequestPatientRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RequestPatientPath(Table<O> path, ForeignKey<O, RequestPatientRecord> childPath, InverseForeignKey<O, RequestPatientRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RequestPatientPath(Name alias, Table<RequestPatientRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RequestPatientPath as(String alias) {
            return new RequestPatientPath(DSL.name(alias), this);
        }

        @Override
        public RequestPatientPath as(Name alias) {
            return new RequestPatientPath(alias, this);
        }

        @Override
        public RequestPatientPath as(Table<?> alias) {
            return new RequestPatientPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REQUEST_PATIENT_PATIENT_ID, Indexes.IDX_REQUEST_PATIENT_REQUEST_ID);
    }

    @Override
    public UniqueKey<RequestPatientRecord> getPrimaryKey() {
        return Keys.REQUEST_PATIENT_PKEY;
    }

    @Override
    public List<UniqueKey<RequestPatientRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_REQUEST_PATIENT);
    }

    @Override
    public List<ForeignKey<RequestPatientRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REQUEST_PATIENT__FK_REQUEST_PATIENT_PATIENT, Keys.REQUEST_PATIENT__FK_REQUEST_PATIENT_REQUEST);
    }

    private transient PatientPath _patient;

    /**
     * Get the implicit join path to the <code>public.patient</code> table.
     */
    public PatientPath patient() {
        if (_patient == null)
            _patient = new PatientPath(this, Keys.REQUEST_PATIENT__FK_REQUEST_PATIENT_PATIENT, null);

        return _patient;
    }

    private transient RequestPath _request;

    /**
     * Get the implicit join path to the <code>public.request</code> table.
     */
    public RequestPath request() {
        if (_request == null)
            _request = new RequestPath(this, Keys.REQUEST_PATIENT__FK_REQUEST_PATIENT_REQUEST, null);

        return _request;
    }

    @Override
    public RequestPatient as(String alias) {
        return new RequestPatient(DSL.name(alias), this);
    }

    @Override
    public RequestPatient as(Name alias) {
        return new RequestPatient(alias, this);
    }

    @Override
    public RequestPatient as(Table<?> alias) {
        return new RequestPatient(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RequestPatient rename(String name) {
        return new RequestPatient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RequestPatient rename(Name name) {
        return new RequestPatient(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RequestPatient rename(Table<?> name) {
        return new RequestPatient(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RequestPatient where(Condition condition) {
        return new RequestPatient(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RequestPatient where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RequestPatient where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RequestPatient where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RequestPatient where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RequestPatient where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RequestPatient where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RequestPatient where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RequestPatient whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RequestPatient whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
