/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.tables.ClinicEmail;
import com.lifelinecalllog.jooq.tables.records.ClinicEmailRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicEmailDao extends DAOImpl<ClinicEmailRecord, com.lifelinecalllog.jooq.tables.pojos.ClinicEmail, UUID> {

    /**
     * Create a new ClinicEmailDao without any configuration
     */
    public ClinicEmailDao() {
        super(ClinicEmail.CLINIC_EMAIL, com.lifelinecalllog.jooq.tables.pojos.ClinicEmail.class);
    }

    /**
     * Create a new ClinicEmailDao with an attached configuration
     */
    public ClinicEmailDao(Configuration configuration) {
        super(ClinicEmail.CLINIC_EMAIL, com.lifelinecalllog.jooq.tables.pojos.ClinicEmail.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.ClinicEmail object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchById(UUID... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.ClinicEmail fetchOneById(UUID value) {
        return fetchOne(ClinicEmail.CLINIC_EMAIL.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchOptionalById(UUID value) {
        return fetchOptional(ClinicEmail.CLINIC_EMAIL.ID, value);
    }

    /**
     * Fetch records that have <code>clinic_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfClinicId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.CLINIC_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>clinic_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByClinicId(UUID... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.CLINIC_ID, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByEmail(String... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.EMAIL, values);
    }

    /**
     * Fetch records that have <code>label BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfLabel(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.LABEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByLabel(String... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.LABEL, values);
    }

    /**
     * Fetch records that have <code>is_primary BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfIsPrimary(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.IS_PRIMARY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_primary IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByIsPrimary(Boolean... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.IS_PRIMARY, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfCreatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByCreatedBy(String... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfLastModifiedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByLastModifiedBy(String... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ClinicEmail.CLINIC_EMAIL.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicEmail> fetchByVersion(Integer... values) {
        return fetch(ClinicEmail.CLINIC_EMAIL.VERSION, values);
    }
}
