/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.tables.Clinic;
import com.lifelinecalllog.jooq.tables.records.ClinicRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicDao extends DAOImpl<ClinicRecord, com.lifelinecalllog.jooq.tables.pojos.Clinic, UUID> {

    /**
     * Create a new ClinicDao without any configuration
     */
    public ClinicDao() {
        super(Clinic.CLINIC, com.lifelinecalllog.jooq.tables.pojos.Clinic.class);
    }

    /**
     * Create a new ClinicDao with an attached configuration
     */
    public ClinicDao(Configuration configuration) {
        super(Clinic.CLINIC, com.lifelinecalllog.jooq.tables.pojos.Clinic.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.Clinic object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Clinic.CLINIC.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchById(UUID... values) {
        return fetch(Clinic.CLINIC.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.Clinic fetchOneById(UUID value) {
        return fetchOne(Clinic.CLINIC.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchOptionalById(UUID value) {
        return fetchOptional(Clinic.CLINIC.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Clinic.CLINIC.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByName(String... values) {
        return fetch(Clinic.CLINIC.NAME, values);
    }

    /**
     * Fetch records that have <code>phone BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(Clinic.CLINIC.PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByPhone(String... values) {
        return fetch(Clinic.CLINIC.PHONE, values);
    }

    /**
     * Fetch records that have <code>fax BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfFax(String lowerInclusive, String upperInclusive) {
        return fetchRange(Clinic.CLINIC.FAX, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fax IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByFax(String... values) {
        return fetch(Clinic.CLINIC.FAX, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Clinic.CLINIC.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByActive(Boolean... values) {
        return fetch(Clinic.CLINIC.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Clinic.CLINIC.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(Clinic.CLINIC.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Clinic.CLINIC.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByCreatedBy(UUID... values) {
        return fetch(Clinic.CLINIC.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Clinic.CLINIC.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(Clinic.CLINIC.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Clinic.CLINIC.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByLastModifiedBy(UUID... values) {
        return fetch(Clinic.CLINIC.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Clinic.CLINIC.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Clinic> fetchByVersion(Integer... values) {
        return fetch(Clinic.CLINIC.VERSION, values);
    }
}
