/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.tables.ClinicLocationEmail;
import com.lifelinecalllog.jooq.tables.records.ClinicLocationEmailRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicLocationEmailDao extends DAOImpl<ClinicLocationEmailRecord, com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail, UUID> {

    /**
     * Create a new ClinicLocationEmailDao without any configuration
     */
    public ClinicLocationEmailDao() {
        super(ClinicLocationEmail.CLINIC_LOCATION_EMAIL, com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail.class);
    }

    /**
     * Create a new ClinicLocationEmailDao with an attached configuration
     */
    public ClinicLocationEmailDao(Configuration configuration) {
        super(ClinicLocationEmail.CLINIC_LOCATION_EMAIL, com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchById(UUID... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail fetchOneById(UUID value) {
        return fetchOne(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchOptionalById(UUID value) {
        return fetchOptional(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.ID, value);
    }

    /**
     * Fetch records that have <code>clinic_location_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfClinicLocationId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CLINIC_LOCATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>clinic_location_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByClinicLocationId(UUID... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CLINIC_LOCATION_ID, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByEmail(String... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.EMAIL, values);
    }

    /**
     * Fetch records that have <code>label BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfLabel(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.LABEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByLabel(String... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.LABEL, values);
    }

    /**
     * Fetch records that have <code>is_primary BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfIsPrimary(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.IS_PRIMARY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_primary IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByIsPrimary(Boolean... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.IS_PRIMARY, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfCreatedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByCreatedBy(String... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfLastModifiedBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByLastModifiedBy(String... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmail> fetchByVersion(Integer... values) {
        return fetch(ClinicLocationEmail.CLINIC_LOCATION_EMAIL.VERSION, values);
    }
}
