/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.tables.Doctor;
import com.lifelinecalllog.jooq.tables.records.DoctorRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DoctorDao extends DAOImpl<DoctorRecord, com.lifelinecalllog.jooq.tables.pojos.Doctor, UUID> {

    /**
     * Create a new DoctorDao without any configuration
     */
    public DoctorDao() {
        super(Doctor.DOCTOR, com.lifelinecalllog.jooq.tables.pojos.Doctor.class);
    }

    /**
     * Create a new DoctorDao with an attached configuration
     */
    public DoctorDao(Configuration configuration) {
        super(Doctor.DOCTOR, com.lifelinecalllog.jooq.tables.pojos.Doctor.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.Doctor object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Doctor.DOCTOR.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchById(UUID... values) {
        return fetch(Doctor.DOCTOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.Doctor fetchOneById(UUID value) {
        return fetchOne(Doctor.DOCTOR.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchOptionalById(UUID value) {
        return fetchOptional(Doctor.DOCTOR.ID, value);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByFirstName(String... values) {
        return fetch(Doctor.DOCTOR.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByLastName(String... values) {
        return fetch(Doctor.DOCTOR.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>provider_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfProviderNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.PROVIDER_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>provider_number IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByProviderNumber(String... values) {
        return fetch(Doctor.DOCTOR.PROVIDER_NUMBER, values);
    }

    /**
     * Fetch records that have <code>phone BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByPhone(String... values) {
        return fetch(Doctor.DOCTOR.PHONE, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByEmail(String... values) {
        return fetch(Doctor.DOCTOR.EMAIL, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Doctor.DOCTOR.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByActive(Boolean... values) {
        return fetch(Doctor.DOCTOR.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Doctor.DOCTOR.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(Doctor.DOCTOR.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Doctor.DOCTOR.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByCreatedBy(UUID... values) {
        return fetch(Doctor.DOCTOR.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Doctor.DOCTOR.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(Doctor.DOCTOR.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Doctor.DOCTOR.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByLastModifiedBy(UUID... values) {
        return fetch(Doctor.DOCTOR.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Doctor.DOCTOR.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByVersion(Integer... values) {
        return fetch(Doctor.DOCTOR.VERSION, values);
    }

    /**
     * Fetch records that have <code>prescriber_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchRangeOfPrescriberNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Doctor.DOCTOR.PRESCRIBER_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>prescriber_no IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Doctor> fetchByPrescriberNo(String... values) {
        return fetch(Doctor.DOCTOR.PRESCRIBER_NO, values);
    }
}
