/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.enums.PatientStatus;
import com.lifelinecalllog.jooq.tables.Patient;
import com.lifelinecalllog.jooq.tables.records.PatientRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientDao extends DAOImpl<PatientRecord, com.lifelinecalllog.jooq.tables.pojos.Patient, UUID> {

    /**
     * Create a new PatientDao without any configuration
     */
    public PatientDao() {
        super(Patient.PATIENT, com.lifelinecalllog.jooq.tables.pojos.Patient.class);
    }

    /**
     * Create a new PatientDao with an attached configuration
     */
    public PatientDao(Configuration configuration) {
        super(Patient.PATIENT, com.lifelinecalllog.jooq.tables.pojos.Patient.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.Patient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Patient.PATIENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchById(UUID... values) {
        return fetch(Patient.PATIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.Patient fetchOneById(UUID value) {
        return fetchOne(Patient.PATIENT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchOptionalById(UUID value) {
        return fetchOptional(Patient.PATIENT.ID, value);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByFirstName(String... values) {
        return fetch(Patient.PATIENT.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByLastName(String... values) {
        return fetch(Patient.PATIENT.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>date_of_birth BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfDateOfBirth(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Patient.PATIENT.DATE_OF_BIRTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date_of_birth IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByDateOfBirth(LocalDate... values) {
        return fetch(Patient.PATIENT.DATE_OF_BIRTH, values);
    }

    /**
     * Fetch records that have <code>phone BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByPhone(String... values) {
        return fetch(Patient.PATIENT.PHONE, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Patient.PATIENT.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(Patient.PATIENT.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Patient.PATIENT.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByCreatedBy(UUID... values) {
        return fetch(Patient.PATIENT.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Patient.PATIENT.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(Patient.PATIENT.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Patient.PATIENT.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByLastModifiedBy(UUID... values) {
        return fetch(Patient.PATIENT.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Patient.PATIENT.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByVersion(Integer... values) {
        return fetch(Patient.PATIENT.VERSION, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfStatus(PatientStatus lowerInclusive, PatientStatus upperInclusive) {
        return fetchRange(Patient.PATIENT.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByStatus(PatientStatus... values) {
        return fetch(Patient.PATIENT.STATUS, values);
    }

    /**
     * Fetch records that have <code>status_reason BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfStatusReason(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.STATUS_REASON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status_reason IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByStatusReason(String... values) {
        return fetch(Patient.PATIENT.STATUS_REASON, values);
    }

    /**
     * Fetch records that have <code>deceased_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfDeceasedDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Patient.PATIENT.DECEASED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deceased_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByDeceasedDate(LocalDate... values) {
        return fetch(Patient.PATIENT.DECEASED_DATE, values);
    }

    /**
     * Fetch records that have <code>medicare_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfMedicareNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.MEDICARE_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>medicare_no IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByMedicareNo(String... values) {
        return fetch(Patient.PATIENT.MEDICARE_NO, values);
    }

    /**
     * Fetch records that have <code>irn_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfIrnNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.IRN_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>irn_no IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByIrnNo(String... values) {
        return fetch(Patient.PATIENT.IRN_NO, values);
    }

    /**
     * Fetch records that have <code>remark BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchRangeOfRemark(String lowerInclusive, String upperInclusive) {
        return fetchRange(Patient.PATIENT.REMARK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Patient> fetchByRemark(String... values) {
        return fetch(Patient.PATIENT.REMARK, values);
    }
}
