/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.tables.Request;
import com.lifelinecalllog.jooq.tables.records.RequestRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RequestDao extends DAOImpl<RequestRecord, com.lifelinecalllog.jooq.tables.pojos.Request, UUID> {

    /**
     * Create a new RequestDao without any configuration
     */
    public RequestDao() {
        super(Request.REQUEST, com.lifelinecalllog.jooq.tables.pojos.Request.class);
    }

    /**
     * Create a new RequestDao with an attached configuration
     */
    public RequestDao(Configuration configuration) {
        super(Request.REQUEST, com.lifelinecalllog.jooq.tables.pojos.Request.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.Request object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchById(UUID... values) {
        return fetch(Request.REQUEST.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.Request fetchOneById(UUID value) {
        return fetchOne(Request.REQUEST.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.Request> fetchOptionalById(UUID value) {
        return fetchOptional(Request.REQUEST.ID, value);
    }

    /**
     * Fetch records that have <code>clinic_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfClinicId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.CLINIC_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>clinic_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByClinicId(UUID... values) {
        return fetch(Request.REQUEST.CLINIC_ID, values);
    }

    /**
     * Fetch records that have <code>doctor_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfDoctorId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.DOCTOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>doctor_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByDoctorId(UUID... values) {
        return fetch(Request.REQUEST.DOCTOR_ID, values);
    }

    /**
     * Fetch records that have <code>visit_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfVisitType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Request.REQUEST.VISIT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>visit_type IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByVisitType(String... values) {
        return fetch(Request.REQUEST.VISIT_TYPE, values);
    }

    /**
     * Fetch records that have <code>urgency BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfUrgency(String lowerInclusive, String upperInclusive) {
        return fetchRange(Request.REQUEST.URGENCY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>urgency IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByUrgency(String... values) {
        return fetch(Request.REQUEST.URGENCY, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Request.REQUEST.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByStatus(String... values) {
        return fetch(Request.REQUEST.STATUS, values);
    }

    /**
     * Fetch records that have <code>request_details BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfRequestDetails(String lowerInclusive, String upperInclusive) {
        return fetchRange(Request.REQUEST.REQUEST_DETAILS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>request_details IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByRequestDetails(String... values) {
        return fetch(Request.REQUEST.REQUEST_DETAILS, values);
    }

    /**
     * Fetch records that have <code>received_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfReceivedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Request.REQUEST.RECEIVED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>received_at IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByReceivedAt(OffsetDateTime... values) {
        return fetch(Request.REQUEST.RECEIVED_AT, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Request.REQUEST.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(Request.REQUEST.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByCreatedBy(UUID... values) {
        return fetch(Request.REQUEST.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Request.REQUEST.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(Request.REQUEST.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByLastModifiedBy(UUID... values) {
        return fetch(Request.REQUEST.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Request.REQUEST.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByVersion(Integer... values) {
        return fetch(Request.REQUEST.VERSION, values);
    }

    /**
     * Fetch records that have <code>start_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfStartTime(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Request.REQUEST.START_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByStartTime(OffsetDateTime... values) {
        return fetch(Request.REQUEST.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfEndTime(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Request.REQUEST.END_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByEndTime(OffsetDateTime... values) {
        return fetch(Request.REQUEST.END_TIME, values);
    }

    /**
     * Fetch records that have <code>clinic_location_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfClinicLocationId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.CLINIC_LOCATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>clinic_location_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByClinicLocationId(UUID... values) {
        return fetch(Request.REQUEST.CLINIC_LOCATION_ID, values);
    }

    /**
     * Fetch records that have <code>entered_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchRangeOfEnteredBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(Request.REQUEST.ENTERED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>entered_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.Request> fetchByEnteredBy(UUID... values) {
        return fetch(Request.REQUEST.ENTERED_BY, values);
    }
}
