/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.daos;


import com.lifelinecalllog.jooq.tables.RequestPatient;
import com.lifelinecalllog.jooq.tables.records.RequestPatientRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RequestPatientDao extends DAOImpl<RequestPatientRecord, com.lifelinecalllog.jooq.tables.pojos.RequestPatient, UUID> {

    /**
     * Create a new RequestPatientDao without any configuration
     */
    public RequestPatientDao() {
        super(RequestPatient.REQUEST_PATIENT, com.lifelinecalllog.jooq.tables.pojos.RequestPatient.class);
    }

    /**
     * Create a new RequestPatientDao with an attached configuration
     */
    public RequestPatientDao(Configuration configuration) {
        super(RequestPatient.REQUEST_PATIENT, com.lifelinecalllog.jooq.tables.pojos.RequestPatient.class, configuration);
    }

    @Override
    public UUID getId(com.lifelinecalllog.jooq.tables.pojos.RequestPatient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchById(UUID... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.lifelinecalllog.jooq.tables.pojos.RequestPatient fetchOneById(UUID value) {
        return fetchOne(RequestPatient.REQUEST_PATIENT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchOptionalById(UUID value) {
        return fetchOptional(RequestPatient.REQUEST_PATIENT.ID, value);
    }

    /**
     * Fetch records that have <code>request_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfRequestId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.REQUEST_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>request_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByRequestId(UUID... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.REQUEST_ID, values);
    }

    /**
     * Fetch records that have <code>patient_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfPatientId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.PATIENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>patient_id IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByPatientId(UUID... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.PATIENT_ID, values);
    }

    /**
     * Fetch records that have <code>notes BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfNotes(String lowerInclusive, String upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.NOTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notes IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByNotes(String... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.NOTES, values);
    }

    /**
     * Fetch records that have <code>created_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfCreatedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.CREATED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByCreatedDate(OffsetDateTime... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfCreatedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByCreatedBy(UUID... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>last_modified_date BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfLastModifiedDate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.LAST_MODIFIED_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_date IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByLastModifiedDate(OffsetDateTime... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.LAST_MODIFIED_DATE, values);
    }

    /**
     * Fetch records that have <code>last_modified_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfLastModifiedBy(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.LAST_MODIFIED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modified_by IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByLastModifiedBy(UUID... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.LAST_MODIFIED_BY, values);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchRangeOfVersion(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(RequestPatient.REQUEST_PATIENT.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<com.lifelinecalllog.jooq.tables.pojos.RequestPatient> fetchByVersion(Integer... values) {
        return fetch(RequestPatient.REQUEST_PATIENT.VERSION, values);
    }
}
