/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.AppUser;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_user.id</code>.
     */
    public AppUserRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.app_user.username</code>.
     */
    public AppUserRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_user.email</code>.
     */
    public AppUserRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_user.password_hash</code>.
     */
    public AppUserRecord setPasswordHash(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_user.first_name</code>.
     */
    public AppUserRecord setFirstName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_user.last_name</code>.
     */
    public AppUserRecord setLastName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.app_user.role</code>.
     */
    public AppUserRecord setRole(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.role</code>.
     */
    public String getRole() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.app_user.enabled</code>.
     */
    public AppUserRecord setEnabled(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.app_user.created_date</code>.
     */
    public AppUserRecord setCreatedDate(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.app_user.created_by</code>.
     */
    public AppUserRecord setCreatedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.app_user.last_modified_date</code>.
     */
    public AppUserRecord setLastModifiedDate(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.app_user.last_modified_by</code>.
     */
    public AppUserRecord setLastModifiedBy(UUID value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.app_user.version</code>.
     */
    public AppUserRecord setVersion(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.app_user.failed_login_attempts</code>.
     */
    public AppUserRecord setFailedLoginAttempts(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.failed_login_attempts</code>.
     */
    public Integer getFailedLoginAttempts() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.app_user.locked_until</code>.
     */
    public AppUserRecord setLockedUntil(OffsetDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user.locked_until</code>.
     */
    public OffsetDateTime getLockedUntil() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(UUID id, String username, String email, String passwordHash, String firstName, String lastName, String role, Boolean enabled, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, Integer failedLoginAttempts, OffsetDateTime lockedUntil) {
        super(AppUser.APP_USER);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPasswordHash(passwordHash);
        setFirstName(firstName);
        setLastName(lastName);
        setRole(role);
        setEnabled(enabled);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setFailedLoginAttempts(failedLoginAttempts);
        setLockedUntil(lockedUntil);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(com.lifelinecalllog.jooq.tables.pojos.AppUser value) {
        super(AppUser.APP_USER);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setPasswordHash(value.getPasswordHash());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setRole(value.getRole());
            setEnabled(value.getEnabled());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setFailedLoginAttempts(value.getFailedLoginAttempts());
            setLockedUntil(value.getLockedUntil());
            resetChangedOnNotNull();
        }
    }
}
