/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.AppUserHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserHistoryRecord extends TableRecordImpl<AppUserHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_user_history.id</code>.
     */
    public AppUserHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.app_user_history.username</code>.
     */
    public AppUserHistoryRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_user_history.email</code>.
     */
    public AppUserHistoryRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_user_history.password_hash</code>.
     */
    public AppUserHistoryRecord setPasswordHash(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_user_history.first_name</code>.
     */
    public AppUserHistoryRecord setFirstName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_user_history.last_name</code>.
     */
    public AppUserHistoryRecord setLastName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.app_user_history.role</code>.
     */
    public AppUserHistoryRecord setRole(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.role</code>.
     */
    public String getRole() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.app_user_history.enabled</code>.
     */
    public AppUserHistoryRecord setEnabled(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.app_user_history.created_date</code>.
     */
    public AppUserHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.app_user_history.created_by</code>.
     */
    public AppUserHistoryRecord setCreatedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.app_user_history.last_modified_date</code>.
     */
    public AppUserHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.app_user_history.last_modified_by</code>.
     */
    public AppUserHistoryRecord setLastModifiedBy(UUID value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.app_user_history.version</code>.
     */
    public AppUserHistoryRecord setVersion(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.app_user_history.dml_type</code>.
     */
    public AppUserHistoryRecord setDmlType(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.app_user_history.history_created_date</code>.
     */
    public AppUserHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.app_user_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserHistoryRecord
     */
    public AppUserHistoryRecord() {
        super(AppUserHistory.APP_USER_HISTORY);
    }

    /**
     * Create a detached, initialised AppUserHistoryRecord
     */
    public AppUserHistoryRecord(UUID id, String username, String email, String passwordHash, String firstName, String lastName, String role, Boolean enabled, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(AppUserHistory.APP_USER_HISTORY);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPasswordHash(passwordHash);
        setFirstName(firstName);
        setLastName(lastName);
        setRole(role);
        setEnabled(enabled);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AppUserHistoryRecord
     */
    public AppUserHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.AppUserHistory value) {
        super(AppUserHistory.APP_USER_HISTORY);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setPasswordHash(value.getPasswordHash());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setRole(value.getRole());
            setEnabled(value.getEnabled());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
