/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.ClinicEmail;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicEmailRecord extends UpdatableRecordImpl<ClinicEmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clinic_email.id</code>.
     */
    public ClinicEmailRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clinic_email.clinic_id</code>.
     */
    public ClinicEmailRecord setClinicId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.clinic_id</code>.
     */
    public UUID getClinicId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clinic_email.email</code>.
     */
    public ClinicEmailRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clinic_email.label</code>.
     */
    public ClinicEmailRecord setLabel(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clinic_email.is_primary</code>.
     */
    public ClinicEmailRecord setIsPrimary(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.clinic_email.created_date</code>.
     */
    public ClinicEmailRecord setCreatedDate(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.clinic_email.created_by</code>.
     */
    public ClinicEmailRecord setCreatedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.clinic_email.last_modified_date</code>.
     */
    public ClinicEmailRecord setLastModifiedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.clinic_email.last_modified_by</code>.
     */
    public ClinicEmailRecord setLastModifiedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.clinic_email.version</code>.
     */
    public ClinicEmailRecord setVersion(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClinicEmailRecord
     */
    public ClinicEmailRecord() {
        super(ClinicEmail.CLINIC_EMAIL);
    }

    /**
     * Create a detached, initialised ClinicEmailRecord
     */
    public ClinicEmailRecord(UUID id, UUID clinicId, String email, String label, Boolean isPrimary, OffsetDateTime createdDate, String createdBy, OffsetDateTime lastModifiedDate, String lastModifiedBy, Integer version) {
        super(ClinicEmail.CLINIC_EMAIL);

        setId(id);
        setClinicId(clinicId);
        setEmail(email);
        setLabel(label);
        setIsPrimary(isPrimary);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ClinicEmailRecord
     */
    public ClinicEmailRecord(com.lifelinecalllog.jooq.tables.pojos.ClinicEmail value) {
        super(ClinicEmail.CLINIC_EMAIL);

        if (value != null) {
            setId(value.getId());
            setClinicId(value.getClinicId());
            setEmail(value.getEmail());
            setLabel(value.getLabel());
            setIsPrimary(value.getIsPrimary());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
