/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.ClinicLocationEmailHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicLocationEmailHistoryRecord extends TableRecordImpl<ClinicLocationEmailHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clinic_location_email_history.id</code>.
     */
    public ClinicLocationEmailHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.clinic_location_email_history.clinic_location_id</code>.
     */
    public ClinicLocationEmailHistoryRecord setClinicLocationId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.clinic_location_email_history.clinic_location_id</code>.
     */
    public UUID getClinicLocationId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clinic_location_email_history.email</code>.
     */
    public ClinicLocationEmailHistoryRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clinic_location_email_history.label</code>.
     */
    public ClinicLocationEmailHistoryRecord setLabel(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clinic_location_email_history.is_primary</code>.
     */
    public ClinicLocationEmailHistoryRecord setIsPrimary(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(4);
    }

    /**
     * Setter for
     * <code>public.clinic_location_email_history.created_date</code>.
     */
    public ClinicLocationEmailHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.clinic_location_email_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.clinic_location_email_history.created_by</code>.
     */
    public ClinicLocationEmailHistoryRecord setCreatedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.clinic_location_email_history.last_modified_date</code>.
     */
    public ClinicLocationEmailHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.clinic_location_email_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for
     * <code>public.clinic_location_email_history.last_modified_by</code>.
     */
    public ClinicLocationEmailHistoryRecord setLastModifiedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.clinic_location_email_history.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.clinic_location_email_history.version</code>.
     */
    public ClinicLocationEmailHistoryRecord setVersion(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.clinic_location_email_history.dml_type</code>.
     */
    public ClinicLocationEmailHistoryRecord setDmlType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location_email_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public.clinic_location_email_history.history_created_date</code>.
     */
    public ClinicLocationEmailHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.clinic_location_email_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClinicLocationEmailHistoryRecord
     */
    public ClinicLocationEmailHistoryRecord() {
        super(ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY);
    }

    /**
     * Create a detached, initialised ClinicLocationEmailHistoryRecord
     */
    public ClinicLocationEmailHistoryRecord(UUID id, UUID clinicLocationId, String email, String label, Boolean isPrimary, OffsetDateTime createdDate, String createdBy, OffsetDateTime lastModifiedDate, String lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY);

        setId(id);
        setClinicLocationId(clinicLocationId);
        setEmail(email);
        setLabel(label);
        setIsPrimary(isPrimary);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ClinicLocationEmailHistoryRecord
     */
    public ClinicLocationEmailHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.ClinicLocationEmailHistory value) {
        super(ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY);

        if (value != null) {
            setId(value.getId());
            setClinicLocationId(value.getClinicLocationId());
            setEmail(value.getEmail());
            setLabel(value.getLabel());
            setIsPrimary(value.getIsPrimary());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
