/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.ClinicEmailHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicEmailHistoryRecord extends TableRecordImpl<ClinicEmailHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clinic_email_history.id</code>.
     */
    public ClinicEmailHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clinic_email_history.clinic_id</code>.
     */
    public ClinicEmailHistoryRecord setClinicId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.clinic_id</code>.
     */
    public UUID getClinicId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clinic_email_history.email</code>.
     */
    public ClinicEmailHistoryRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clinic_email_history.label</code>.
     */
    public ClinicEmailHistoryRecord setLabel(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clinic_email_history.is_primary</code>.
     */
    public ClinicEmailHistoryRecord setIsPrimary(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.clinic_email_history.created_date</code>.
     */
    public ClinicEmailHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.clinic_email_history.created_by</code>.
     */
    public ClinicEmailHistoryRecord setCreatedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.clinic_email_history.last_modified_date</code>.
     */
    public ClinicEmailHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.clinic_email_history.last_modified_by</code>.
     */
    public ClinicEmailHistoryRecord setLastModifiedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.clinic_email_history.version</code>.
     */
    public ClinicEmailHistoryRecord setVersion(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.clinic_email_history.dml_type</code>.
     */
    public ClinicEmailHistoryRecord setDmlType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.clinic_email_history.history_created_date</code>.
     */
    public ClinicEmailHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_email_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClinicEmailHistoryRecord
     */
    public ClinicEmailHistoryRecord() {
        super(ClinicEmailHistory.CLINIC_EMAIL_HISTORY);
    }

    /**
     * Create a detached, initialised ClinicEmailHistoryRecord
     */
    public ClinicEmailHistoryRecord(UUID id, UUID clinicId, String email, String label, Boolean isPrimary, OffsetDateTime createdDate, String createdBy, OffsetDateTime lastModifiedDate, String lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(ClinicEmailHistory.CLINIC_EMAIL_HISTORY);

        setId(id);
        setClinicId(clinicId);
        setEmail(email);
        setLabel(label);
        setIsPrimary(isPrimary);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ClinicEmailHistoryRecord
     */
    public ClinicEmailHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.ClinicEmailHistory value) {
        super(ClinicEmailHistory.CLINIC_EMAIL_HISTORY);

        if (value != null) {
            setId(value.getId());
            setClinicId(value.getClinicId());
            setEmail(value.getEmail());
            setLabel(value.getLabel());
            setIsPrimary(value.getIsPrimary());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
