/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.ClinicLocation;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicLocationRecord extends UpdatableRecordImpl<ClinicLocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clinic_location.id</code>.
     */
    public ClinicLocationRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clinic_location.clinic_id</code>.
     */
    public ClinicLocationRecord setClinicId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.clinic_id</code>.
     */
    public UUID getClinicId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clinic_location.name</code>.
     */
    public ClinicLocationRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clinic_location.address_line1</code>.
     */
    public ClinicLocationRecord setAddressLine1(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.address_line1</code>.
     */
    public String getAddressLine1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clinic_location.address_line2</code>.
     */
    public ClinicLocationRecord setAddressLine2(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.address_line2</code>.
     */
    public String getAddressLine2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.clinic_location.suburb</code>.
     */
    public ClinicLocationRecord setSuburb(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.suburb</code>.
     */
    public String getSuburb() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.clinic_location.state</code>.
     */
    public ClinicLocationRecord setState(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.state</code>.
     */
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.clinic_location.postcode</code>.
     */
    public ClinicLocationRecord setPostcode(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.postcode</code>.
     */
    public String getPostcode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.clinic_location.latitude</code>.
     */
    public ClinicLocationRecord setLatitude(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.clinic_location.longitude</code>.
     */
    public ClinicLocationRecord setLongitude(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.clinic_location.place_id</code>.
     */
    public ClinicLocationRecord setPlaceId(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.place_id</code>.
     */
    public String getPlaceId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.clinic_location.formatted_address</code>.
     */
    public ClinicLocationRecord setFormattedAddress(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.formatted_address</code>.
     */
    public String getFormattedAddress() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.clinic_location.manager_name</code>.
     */
    public ClinicLocationRecord setManagerName(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.manager_name</code>.
     */
    public String getManagerName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.clinic_location.care_coordination_name</code>.
     */
    public ClinicLocationRecord setCareCoordinationName(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.care_coordination_name</code>.
     */
    public String getCareCoordinationName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.clinic_location.phone</code>.
     */
    public ClinicLocationRecord setPhone(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.phone</code>.
     */
    public String getPhone() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.clinic_location.fax</code>.
     */
    public ClinicLocationRecord setFax(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.fax</code>.
     */
    public String getFax() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.clinic_location.is_primary</code>.
     */
    public ClinicLocationRecord setIsPrimary(Boolean value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.clinic_location.active</code>.
     */
    public ClinicLocationRecord setActive(Boolean value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.clinic_location.created_date</code>.
     */
    public ClinicLocationRecord setCreatedDate(OffsetDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(18);
    }

    /**
     * Setter for <code>public.clinic_location.created_by</code>.
     */
    public ClinicLocationRecord setCreatedBy(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.clinic_location.last_modified_date</code>.
     */
    public ClinicLocationRecord setLastModifiedDate(OffsetDateTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(20);
    }

    /**
     * Setter for <code>public.clinic_location.last_modified_by</code>.
     */
    public ClinicLocationRecord setLastModifiedBy(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.clinic_location.version</code>.
     */
    public ClinicLocationRecord setVersion(Integer value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_location.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClinicLocationRecord
     */
    public ClinicLocationRecord() {
        super(ClinicLocation.CLINIC_LOCATION);
    }

    /**
     * Create a detached, initialised ClinicLocationRecord
     */
    public ClinicLocationRecord(UUID id, UUID clinicId, String name, String addressLine1, String addressLine2, String suburb, String state, String postcode, BigDecimal latitude, BigDecimal longitude, String placeId, String formattedAddress, String managerName, String careCoordinationName, String phone, String fax, Boolean isPrimary, Boolean active, OffsetDateTime createdDate, String createdBy, OffsetDateTime lastModifiedDate, String lastModifiedBy, Integer version) {
        super(ClinicLocation.CLINIC_LOCATION);

        setId(id);
        setClinicId(clinicId);
        setName(name);
        setAddressLine1(addressLine1);
        setAddressLine2(addressLine2);
        setSuburb(suburb);
        setState(state);
        setPostcode(postcode);
        setLatitude(latitude);
        setLongitude(longitude);
        setPlaceId(placeId);
        setFormattedAddress(formattedAddress);
        setManagerName(managerName);
        setCareCoordinationName(careCoordinationName);
        setPhone(phone);
        setFax(fax);
        setIsPrimary(isPrimary);
        setActive(active);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ClinicLocationRecord
     */
    public ClinicLocationRecord(com.lifelinecalllog.jooq.tables.pojos.ClinicLocation value) {
        super(ClinicLocation.CLINIC_LOCATION);

        if (value != null) {
            setId(value.getId());
            setClinicId(value.getClinicId());
            setName(value.getName());
            setAddressLine1(value.getAddressLine1());
            setAddressLine2(value.getAddressLine2());
            setSuburb(value.getSuburb());
            setState(value.getState());
            setPostcode(value.getPostcode());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setPlaceId(value.getPlaceId());
            setFormattedAddress(value.getFormattedAddress());
            setManagerName(value.getManagerName());
            setCareCoordinationName(value.getCareCoordinationName());
            setPhone(value.getPhone());
            setFax(value.getFax());
            setIsPrimary(value.getIsPrimary());
            setActive(value.getActive());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
