/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.ClinicHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClinicHistoryRecord extends TableRecordImpl<ClinicHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clinic_history.id</code>.
     */
    public ClinicHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clinic_history.name</code>.
     */
    public ClinicHistoryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.clinic_history.address</code>.
     */
    public ClinicHistoryRecord setAddress(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clinic_history.phone</code>.
     */
    public ClinicHistoryRecord setPhone(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clinic_history.fax</code>.
     */
    public ClinicHistoryRecord setFax(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.fax</code>.
     */
    public String getFax() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.clinic_history.email</code>.
     */
    public ClinicHistoryRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.clinic_history.active</code>.
     */
    public ClinicHistoryRecord setActive(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.clinic_history.created_date</code>.
     */
    public ClinicHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.clinic_history.created_by</code>.
     */
    public ClinicHistoryRecord setCreatedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.clinic_history.last_modified_date</code>.
     */
    public ClinicHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.clinic_history.last_modified_by</code>.
     */
    public ClinicHistoryRecord setLastModifiedBy(UUID value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>public.clinic_history.version</code>.
     */
    public ClinicHistoryRecord setVersion(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.clinic_history.dml_type</code>.
     */
    public ClinicHistoryRecord setDmlType(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.clinic_history.history_created_date</code>.
     */
    public ClinicHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.clinic_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClinicHistoryRecord
     */
    public ClinicHistoryRecord() {
        super(ClinicHistory.CLINIC_HISTORY);
    }

    /**
     * Create a detached, initialised ClinicHistoryRecord
     */
    public ClinicHistoryRecord(UUID id, String name, String address, String phone, String fax, String email, Boolean active, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(ClinicHistory.CLINIC_HISTORY);

        setId(id);
        setName(name);
        setAddress(address);
        setPhone(phone);
        setFax(fax);
        setEmail(email);
        setActive(active);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ClinicHistoryRecord
     */
    public ClinicHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.ClinicHistory value) {
        super(ClinicHistory.CLINIC_HISTORY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setAddress(value.getAddress());
            setPhone(value.getPhone());
            setFax(value.getFax());
            setEmail(value.getEmail());
            setActive(value.getActive());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
