/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.Configuration;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConfigurationRecord extends UpdatableRecordImpl<ConfigurationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.configuration.config_group</code>.
     */
    public ConfigurationRecord setConfigGroup(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.config_group</code>.
     */
    public String getConfigGroup() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.configuration.group_display_order</code>.
     */
    public ConfigurationRecord setGroupDisplayOrder(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.group_display_order</code>.
     */
    public Integer getGroupDisplayOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.configuration.config_key</code>.
     */
    public ConfigurationRecord setConfigKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.config_key</code>.
     */
    public String getConfigKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.configuration.config_description</code>.
     */
    public ConfigurationRecord setConfigDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.config_description</code>.
     */
    public String getConfigDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.configuration.config_display_order</code>.
     */
    public ConfigurationRecord setConfigDisplayOrder(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.config_display_order</code>.
     */
    public Integer getConfigDisplayOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.configuration.status</code>.
     */
    public ConfigurationRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.configuration.created_date</code>.
     */
    public ConfigurationRecord setCreatedDate(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.configuration.created_by</code>.
     */
    public ConfigurationRecord setCreatedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.configuration.last_modified_date</code>.
     */
    public ConfigurationRecord setLastModifiedDate(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.configuration.last_modified_by</code>.
     */
    public ConfigurationRecord setLastModifiedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.configuration.version</code>.
     */
    public ConfigurationRecord setVersion(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigurationRecord
     */
    public ConfigurationRecord() {
        super(Configuration.CONFIGURATION);
    }

    /**
     * Create a detached, initialised ConfigurationRecord
     */
    public ConfigurationRecord(String configGroup, Integer groupDisplayOrder, String configKey, String configDescription, Integer configDisplayOrder, String status, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version) {
        super(Configuration.CONFIGURATION);

        setConfigGroup(configGroup);
        setGroupDisplayOrder(groupDisplayOrder);
        setConfigKey(configKey);
        setConfigDescription(configDescription);
        setConfigDisplayOrder(configDisplayOrder);
        setStatus(status);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ConfigurationRecord
     */
    public ConfigurationRecord(com.lifelinecalllog.jooq.tables.pojos.Configuration value) {
        super(Configuration.CONFIGURATION);

        if (value != null) {
            setConfigGroup(value.getConfigGroup());
            setGroupDisplayOrder(value.getGroupDisplayOrder());
            setConfigKey(value.getConfigKey());
            setConfigDescription(value.getConfigDescription());
            setConfigDisplayOrder(value.getConfigDisplayOrder());
            setStatus(value.getStatus());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
