/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.ConfigurationHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConfigurationHistoryRecord extends TableRecordImpl<ConfigurationHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.configuration_history.config_group</code>.
     */
    public ConfigurationHistoryRecord setConfigGroup(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.config_group</code>.
     */
    public String getConfigGroup() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.configuration_history.group_display_order</code>.
     */
    public ConfigurationHistoryRecord setGroupDisplayOrder(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.group_display_order</code>.
     */
    public Integer getGroupDisplayOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.configuration_history.config_key</code>.
     */
    public ConfigurationHistoryRecord setConfigKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.config_key</code>.
     */
    public String getConfigKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.configuration_history.config_description</code>.
     */
    public ConfigurationHistoryRecord setConfigDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.config_description</code>.
     */
    public String getConfigDescription() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.configuration_history.config_display_order</code>.
     */
    public ConfigurationHistoryRecord setConfigDisplayOrder(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.configuration_history.config_display_order</code>.
     */
    public Integer getConfigDisplayOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.configuration_history.status</code>.
     */
    public ConfigurationHistoryRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.configuration_history.created_date</code>.
     */
    public ConfigurationHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.configuration_history.created_by</code>.
     */
    public ConfigurationHistoryRecord setCreatedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.configuration_history.last_modified_date</code>.
     */
    public ConfigurationHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.configuration_history.last_modified_by</code>.
     */
    public ConfigurationHistoryRecord setLastModifiedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.configuration_history.version</code>.
     */
    public ConfigurationHistoryRecord setVersion(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.configuration_history.dml_type</code>.
     */
    public ConfigurationHistoryRecord setDmlType(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>public.configuration_history.history_created_date</code>.
     */
    public ConfigurationHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.configuration_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigurationHistoryRecord
     */
    public ConfigurationHistoryRecord() {
        super(ConfigurationHistory.CONFIGURATION_HISTORY);
    }

    /**
     * Create a detached, initialised ConfigurationHistoryRecord
     */
    public ConfigurationHistoryRecord(String configGroup, Integer groupDisplayOrder, String configKey, String configDescription, Integer configDisplayOrder, String status, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(ConfigurationHistory.CONFIGURATION_HISTORY);

        setConfigGroup(configGroup);
        setGroupDisplayOrder(groupDisplayOrder);
        setConfigKey(configKey);
        setConfigDescription(configDescription);
        setConfigDisplayOrder(configDisplayOrder);
        setStatus(status);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ConfigurationHistoryRecord
     */
    public ConfigurationHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.ConfigurationHistory value) {
        super(ConfigurationHistory.CONFIGURATION_HISTORY);

        if (value != null) {
            setConfigGroup(value.getConfigGroup());
            setGroupDisplayOrder(value.getGroupDisplayOrder());
            setConfigKey(value.getConfigKey());
            setConfigDescription(value.getConfigDescription());
            setConfigDisplayOrder(value.getConfigDisplayOrder());
            setStatus(value.getStatus());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
