/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.PasswordResetToken;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordResetTokenRecord extends UpdatableRecordImpl<PasswordResetTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.password_reset_token.token</code>.
     */
    public PasswordResetTokenRecord setToken(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.token</code>.
     */
    public String getToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.password_reset_token.user_id</code>.
     */
    public PasswordResetTokenRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.password_reset_token.expires_at</code>.
     */
    public PasswordResetTokenRecord setExpiresAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.password_reset_token.used</code>.
     */
    public PasswordResetTokenRecord setUsed(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.used</code>.
     */
    public Boolean getUsed() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.password_reset_token.created_at</code>.
     */
    public PasswordResetTokenRecord setCreatedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PasswordResetTokenRecord
     */
    public PasswordResetTokenRecord() {
        super(PasswordResetToken.PASSWORD_RESET_TOKEN);
    }

    /**
     * Create a detached, initialised PasswordResetTokenRecord
     */
    public PasswordResetTokenRecord(String token, UUID userId, OffsetDateTime expiresAt, Boolean used, OffsetDateTime createdAt) {
        super(PasswordResetToken.PASSWORD_RESET_TOKEN);

        setToken(token);
        setUserId(userId);
        setExpiresAt(expiresAt);
        setUsed(used);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PasswordResetTokenRecord
     */
    public PasswordResetTokenRecord(com.lifelinecalllog.jooq.tables.pojos.PasswordResetToken value) {
        super(PasswordResetToken.PASSWORD_RESET_TOKEN);

        if (value != null) {
            setToken(value.getToken());
            setUserId(value.getUserId());
            setExpiresAt(value.getExpiresAt());
            setUsed(value.getUsed());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
