/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.enums.PatientStatus;
import com.lifelinecalllog.jooq.tables.PatientHistory;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientHistoryRecord extends TableRecordImpl<PatientHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.patient_history.id</code>.
     */
    public PatientHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.patient_history.first_name</code>.
     */
    public PatientHistoryRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.patient_history.last_name</code>.
     */
    public PatientHistoryRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.patient_history.date_of_birth</code>.
     */
    public PatientHistoryRecord setDateOfBirth(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.patient_history.phone</code>.
     */
    public PatientHistoryRecord setPhone(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.patient_history.created_date</code>.
     */
    public PatientHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.patient_history.created_by</code>.
     */
    public PatientHistoryRecord setCreatedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.patient_history.last_modified_date</code>.
     */
    public PatientHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.patient_history.last_modified_by</code>.
     */
    public PatientHistoryRecord setLastModifiedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.patient_history.version</code>.
     */
    public PatientHistoryRecord setVersion(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.patient_history.dml_type</code>.
     */
    public PatientHistoryRecord setDmlType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.patient_history.history_created_date</code>.
     */
    public PatientHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.patient_history.status</code>.
     */
    public PatientHistoryRecord setStatus(PatientStatus value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.status</code>.
     */
    public PatientStatus getStatus() {
        return (PatientStatus) get(12);
    }

    /**
     * Setter for <code>public.patient_history.status_reason</code>.
     */
    public PatientHistoryRecord setStatusReason(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.status_reason</code>.
     */
    public String getStatusReason() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.patient_history.deceased_date</code>.
     */
    public PatientHistoryRecord setDeceasedDate(LocalDate value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.deceased_date</code>.
     */
    public LocalDate getDeceasedDate() {
        return (LocalDate) get(14);
    }

    /**
     * Setter for <code>public.patient_history.medicare_no</code>.
     */
    public PatientHistoryRecord setMedicareNo(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.medicare_no</code>.
     */
    public String getMedicareNo() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.patient_history.irn_no</code>.
     */
    public PatientHistoryRecord setIrnNo(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.irn_no</code>.
     */
    public String getIrnNo() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.patient_history.remark</code>.
     */
    public PatientHistoryRecord setRemark(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_history.remark</code>.
     */
    public String getRemark() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientHistoryRecord
     */
    public PatientHistoryRecord() {
        super(PatientHistory.PATIENT_HISTORY);
    }

    /**
     * Create a detached, initialised PatientHistoryRecord
     */
    public PatientHistoryRecord(UUID id, String firstName, String lastName, LocalDate dateOfBirth, String phone, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate, PatientStatus status, String statusReason, LocalDate deceasedDate, String medicareNo, String irnNo, String remark) {
        super(PatientHistory.PATIENT_HISTORY);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setDateOfBirth(dateOfBirth);
        setPhone(phone);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        setStatus(status);
        setStatusReason(statusReason);
        setDeceasedDate(deceasedDate);
        setMedicareNo(medicareNo);
        setIrnNo(irnNo);
        setRemark(remark);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PatientHistoryRecord
     */
    public PatientHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.PatientHistory value) {
        super(PatientHistory.PATIENT_HISTORY);

        if (value != null) {
            setId(value.getId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setDateOfBirth(value.getDateOfBirth());
            setPhone(value.getPhone());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            setStatus(value.getStatus());
            setStatusReason(value.getStatusReason());
            setDeceasedDate(value.getDeceasedDate());
            setMedicareNo(value.getMedicareNo());
            setIrnNo(value.getIrnNo());
            setRemark(value.getRemark());
            resetChangedOnNotNull();
        }
    }
}
