/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.PatientClinic;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientClinicRecord extends UpdatableRecordImpl<PatientClinicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.patient_clinic.id</code>.
     */
    public PatientClinicRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.patient_clinic.patient_id</code>.
     */
    public PatientClinicRecord setPatientId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.patient_id</code>.
     */
    public UUID getPatientId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.patient_clinic.clinic_id</code>.
     */
    public PatientClinicRecord setClinicId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.clinic_id</code>.
     */
    public UUID getClinicId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.patient_clinic.is_current</code>.
     */
    public PatientClinicRecord setIsCurrent(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.is_current</code>.
     */
    public Boolean getIsCurrent() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.patient_clinic.created_date</code>.
     */
    public PatientClinicRecord setCreatedDate(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.patient_clinic.created_by</code>.
     */
    public PatientClinicRecord setCreatedBy(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.patient_clinic.last_modified_date</code>.
     */
    public PatientClinicRecord setLastModifiedDate(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.patient_clinic.last_modified_by</code>.
     */
    public PatientClinicRecord setLastModifiedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.patient_clinic.version</code>.
     */
    public PatientClinicRecord setVersion(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.patient_clinic.clinic_location_id</code>.
     */
    public PatientClinicRecord setClinicLocationId(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.patient_clinic.clinic_location_id</code>.
     */
    public UUID getClinicLocationId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientClinicRecord
     */
    public PatientClinicRecord() {
        super(PatientClinic.PATIENT_CLINIC);
    }

    /**
     * Create a detached, initialised PatientClinicRecord
     */
    public PatientClinicRecord(UUID id, UUID patientId, UUID clinicId, Boolean isCurrent, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, UUID clinicLocationId) {
        super(PatientClinic.PATIENT_CLINIC);

        setId(id);
        setPatientId(patientId);
        setClinicId(clinicId);
        setIsCurrent(isCurrent);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setClinicLocationId(clinicLocationId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PatientClinicRecord
     */
    public PatientClinicRecord(com.lifelinecalllog.jooq.tables.pojos.PatientClinic value) {
        super(PatientClinic.PATIENT_CLINIC);

        if (value != null) {
            setId(value.getId());
            setPatientId(value.getPatientId());
            setClinicId(value.getClinicId());
            setIsCurrent(value.getIsCurrent());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setClinicLocationId(value.getClinicLocationId());
            resetChangedOnNotNull();
        }
    }
}
