/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.RefreshTokenHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokenHistoryRecord extends TableRecordImpl<RefreshTokenHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.refresh_token_history.id</code>.
     */
    public RefreshTokenHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.refresh_token_history.token</code>.
     */
    public RefreshTokenHistoryRecord setToken(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.refresh_token_history.user_id</code>.
     */
    public RefreshTokenHistoryRecord setUserId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.refresh_token_history.expiry_date</code>.
     */
    public RefreshTokenHistoryRecord setExpiryDate(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.expiry_date</code>.
     */
    public OffsetDateTime getExpiryDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.refresh_token_history.revoked</code>.
     */
    public RefreshTokenHistoryRecord setRevoked(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.refresh_token_history.created_date</code>.
     */
    public RefreshTokenHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.refresh_token_history.created_by</code>.
     */
    public RefreshTokenHistoryRecord setCreatedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.refresh_token_history.last_modified_date</code>.
     */
    public RefreshTokenHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.refresh_token_history.last_modified_by</code>.
     */
    public RefreshTokenHistoryRecord setLastModifiedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.refresh_token_history.version</code>.
     */
    public RefreshTokenHistoryRecord setVersion(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.refresh_token_history.dml_type</code>.
     */
    public RefreshTokenHistoryRecord setDmlType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public.refresh_token_history.history_created_date</code>.
     */
    public RefreshTokenHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.refresh_token_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokenHistoryRecord
     */
    public RefreshTokenHistoryRecord() {
        super(RefreshTokenHistory.REFRESH_TOKEN_HISTORY);
    }

    /**
     * Create a detached, initialised RefreshTokenHistoryRecord
     */
    public RefreshTokenHistoryRecord(UUID id, String token, UUID userId, OffsetDateTime expiryDate, Boolean revoked, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(RefreshTokenHistory.REFRESH_TOKEN_HISTORY);

        setId(id);
        setToken(token);
        setUserId(userId);
        setExpiryDate(expiryDate);
        setRevoked(revoked);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshTokenHistoryRecord
     */
    public RefreshTokenHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.RefreshTokenHistory value) {
        super(RefreshTokenHistory.REFRESH_TOKEN_HISTORY);

        if (value != null) {
            setId(value.getId());
            setToken(value.getToken());
            setUserId(value.getUserId());
            setExpiryDate(value.getExpiryDate());
            setRevoked(value.getRevoked());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
