/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.tables.RequestPatientHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RequestPatientHistoryRecord extends TableRecordImpl<RequestPatientHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.request_patient_history.id</code>.
     */
    public RequestPatientHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.request_patient_history.request_id</code>.
     */
    public RequestPatientHistoryRecord setRequestId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.request_id</code>.
     */
    public UUID getRequestId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.request_patient_history.patient_id</code>.
     */
    public RequestPatientHistoryRecord setPatientId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.patient_id</code>.
     */
    public UUID getPatientId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.request_patient_history.notes</code>.
     */
    public RequestPatientHistoryRecord setNotes(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.notes</code>.
     */
    public String getNotes() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.request_patient_history.created_date</code>.
     */
    public RequestPatientHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.request_patient_history.created_by</code>.
     */
    public RequestPatientHistoryRecord setCreatedBy(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(5);
    }

    /**
     * Setter for
     * <code>public.request_patient_history.last_modified_date</code>.
     */
    public RequestPatientHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.request_patient_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.request_patient_history.last_modified_by</code>.
     */
    public RequestPatientHistoryRecord setLastModifiedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.request_patient_history.version</code>.
     */
    public RequestPatientHistoryRecord setVersion(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.request_patient_history.dml_type</code>.
     */
    public RequestPatientHistoryRecord setDmlType(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>public.request_patient_history.history_created_date</code>.
     */
    public RequestPatientHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.request_patient_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequestPatientHistoryRecord
     */
    public RequestPatientHistoryRecord() {
        super(RequestPatientHistory.REQUEST_PATIENT_HISTORY);
    }

    /**
     * Create a detached, initialised RequestPatientHistoryRecord
     */
    public RequestPatientHistoryRecord(UUID id, UUID requestId, UUID patientId, String notes, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate) {
        super(RequestPatientHistory.REQUEST_PATIENT_HISTORY);

        setId(id);
        setRequestId(requestId);
        setPatientId(patientId);
        setNotes(notes);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RequestPatientHistoryRecord
     */
    public RequestPatientHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.RequestPatientHistory value) {
        super(RequestPatientHistory.REQUEST_PATIENT_HISTORY);

        if (value != null) {
            setId(value.getId());
            setRequestId(value.getRequestId());
            setPatientId(value.getPatientId());
            setNotes(value.getNotes());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            resetChangedOnNotNull();
        }
    }
}
