/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.records;


import com.lifelinecalllog.jooq.enums.RequestStatus;
import com.lifelinecalllog.jooq.enums.Urgency;
import com.lifelinecalllog.jooq.enums.VisitType;
import com.lifelinecalllog.jooq.tables.RequestHistory;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RequestHistoryRecord extends TableRecordImpl<RequestHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.request_history.id</code>.
     */
    public RequestHistoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.request_history.clinic_id</code>.
     */
    public RequestHistoryRecord setClinicId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.clinic_id</code>.
     */
    public UUID getClinicId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.request_history.doctor_id</code>.
     */
    public RequestHistoryRecord setDoctorId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.doctor_id</code>.
     */
    public UUID getDoctorId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.request_history.visit_type</code>.
     */
    public RequestHistoryRecord setVisitType(VisitType value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.visit_type</code>.
     */
    public VisitType getVisitType() {
        return (VisitType) get(3);
    }

    /**
     * Setter for <code>public.request_history.urgency</code>.
     */
    public RequestHistoryRecord setUrgency(Urgency value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.urgency</code>.
     */
    public Urgency getUrgency() {
        return (Urgency) get(4);
    }

    /**
     * Setter for <code>public.request_history.status</code>.
     */
    public RequestHistoryRecord setStatus(RequestStatus value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.status</code>.
     */
    public RequestStatus getStatus() {
        return (RequestStatus) get(5);
    }

    /**
     * Setter for <code>public.request_history.request_details</code>.
     */
    public RequestHistoryRecord setRequestDetails(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.request_details</code>.
     */
    public String getRequestDetails() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.request_history.received_at</code>.
     */
    public RequestHistoryRecord setReceivedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.received_at</code>.
     */
    public OffsetDateTime getReceivedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.request_history.created_date</code>.
     */
    public RequestHistoryRecord setCreatedDate(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.request_history.created_by</code>.
     */
    public RequestHistoryRecord setCreatedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.request_history.last_modified_date</code>.
     */
    public RequestHistoryRecord setLastModifiedDate(OffsetDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.request_history.last_modified_by</code>.
     */
    public RequestHistoryRecord setLastModifiedBy(UUID value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.request_history.version</code>.
     */
    public RequestHistoryRecord setVersion(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.request_history.dml_type</code>.
     */
    public RequestHistoryRecord setDmlType(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.dml_type</code>.
     */
    public String getDmlType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.request_history.history_created_date</code>.
     */
    public RequestHistoryRecord setHistoryCreatedDate(OffsetDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.request_history.start_time</code>.
     */
    public RequestHistoryRecord setStartTime(OffsetDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.start_time</code>.
     */
    public OffsetDateTime getStartTime() {
        return (OffsetDateTime) get(15);
    }

    /**
     * Setter for <code>public.request_history.end_time</code>.
     */
    public RequestHistoryRecord setEndTime(OffsetDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.request_history.end_time</code>.
     */
    public OffsetDateTime getEndTime() {
        return (OffsetDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequestHistoryRecord
     */
    public RequestHistoryRecord() {
        super(RequestHistory.REQUEST_HISTORY);
    }

    /**
     * Create a detached, initialised RequestHistoryRecord
     */
    public RequestHistoryRecord(UUID id, UUID clinicId, UUID doctorId, VisitType visitType, Urgency urgency, RequestStatus status, String requestDetails, OffsetDateTime receivedAt, OffsetDateTime createdDate, UUID createdBy, OffsetDateTime lastModifiedDate, UUID lastModifiedBy, Integer version, String dmlType, OffsetDateTime historyCreatedDate, OffsetDateTime startTime, OffsetDateTime endTime) {
        super(RequestHistory.REQUEST_HISTORY);

        setId(id);
        setClinicId(clinicId);
        setDoctorId(doctorId);
        setVisitType(visitType);
        setUrgency(urgency);
        setStatus(status);
        setRequestDetails(requestDetails);
        setReceivedAt(receivedAt);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setVersion(version);
        setDmlType(dmlType);
        setHistoryCreatedDate(historyCreatedDate);
        setStartTime(startTime);
        setEndTime(endTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RequestHistoryRecord
     */
    public RequestHistoryRecord(com.lifelinecalllog.jooq.tables.pojos.RequestHistory value) {
        super(RequestHistory.REQUEST_HISTORY);

        if (value != null) {
            setId(value.getId());
            setClinicId(value.getClinicId());
            setDoctorId(value.getDoctorId());
            setVisitType(value.getVisitType());
            setUrgency(value.getUrgency());
            setStatus(value.getStatus());
            setRequestDetails(value.getRequestDetails());
            setReceivedAt(value.getReceivedAt());
            setCreatedDate(value.getCreatedDate());
            setCreatedBy(value.getCreatedBy());
            setLastModifiedDate(value.getLastModifiedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setVersion(value.getVersion());
            setDmlType(value.getDmlType());
            setHistoryCreatedDate(value.getHistoryCreatedDate());
            setStartTime(value.getStartTime());
            setEndTime(value.getEndTime());
            resetChangedOnNotNull();
        }
    }
}
