/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.enums;


import com.lifelinecalllog.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum PatientStatus implements EnumType {

    ACTIVE("ACTIVE"),

    INACTIVE("INACTIVE"),

    DECEASED("DECEASED");

    private final String literal;

    private PatientStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "patient_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static PatientStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PatientStatus.class, literal);
    }
}
