/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq;


import com.lifelinecalllog.jooq.tables.AppUser;
import com.lifelinecalllog.jooq.tables.AppUserHistory;
import com.lifelinecalllog.jooq.tables.Clinic;
import com.lifelinecalllog.jooq.tables.ClinicEmail;
import com.lifelinecalllog.jooq.tables.ClinicEmailHistory;
import com.lifelinecalllog.jooq.tables.ClinicHistory;
import com.lifelinecalllog.jooq.tables.ClinicLocation;
import com.lifelinecalllog.jooq.tables.ClinicLocationEmail;
import com.lifelinecalllog.jooq.tables.ClinicLocationEmailHistory;
import com.lifelinecalllog.jooq.tables.ClinicLocationHistory;
import com.lifelinecalllog.jooq.tables.Doctor;
import com.lifelinecalllog.jooq.tables.DoctorClinic;
import com.lifelinecalllog.jooq.tables.DoctorClinicHistory;
import com.lifelinecalllog.jooq.tables.DoctorHistory;
import com.lifelinecalllog.jooq.tables.PasswordResetToken;
import com.lifelinecalllog.jooq.tables.Patient;
import com.lifelinecalllog.jooq.tables.PatientClinic;
import com.lifelinecalllog.jooq.tables.PatientClinicHistory;
import com.lifelinecalllog.jooq.tables.PatientHistory;
import com.lifelinecalllog.jooq.tables.RefreshToken;
import com.lifelinecalllog.jooq.tables.RefreshTokenHistory;
import com.lifelinecalllog.jooq.tables.Request;
import com.lifelinecalllog.jooq.tables.RequestHistory;
import com.lifelinecalllog.jooq.tables.RequestPatient;
import com.lifelinecalllog.jooq.tables.RequestPatientHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_APP_USER_EMAIL = Internal.createIndex(DSL.name("idx_app_user_email"), AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.EMAIL }, false);
    public static final Index IDX_APP_USER_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_app_user_history_created_date"), AppUserHistory.APP_USER_HISTORY, new OrderField[] { AppUserHistory.APP_USER_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_APP_USER_HISTORY_ID = Internal.createIndex(DSL.name("idx_app_user_history_id"), AppUserHistory.APP_USER_HISTORY, new OrderField[] { AppUserHistory.APP_USER_HISTORY.ID }, false);
    public static final Index IDX_APP_USER_USERNAME = Internal.createIndex(DSL.name("idx_app_user_username"), AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.USERNAME }, false);
    public static final Index IDX_CLINIC_ACTIVE = Internal.createIndex(DSL.name("idx_clinic_active"), Clinic.CLINIC, new OrderField[] { Clinic.CLINIC.ACTIVE }, false);
    public static final Index IDX_CLINIC_EMAIL_CLINIC_ID = Internal.createIndex(DSL.name("idx_clinic_email_clinic_id"), ClinicEmail.CLINIC_EMAIL, new OrderField[] { ClinicEmail.CLINIC_EMAIL.CLINIC_ID }, false);
    public static final Index IDX_CLINIC_EMAIL_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_clinic_email_history_created_date"), ClinicEmailHistory.CLINIC_EMAIL_HISTORY, new OrderField[] { ClinicEmailHistory.CLINIC_EMAIL_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_CLINIC_EMAIL_HISTORY_ID = Internal.createIndex(DSL.name("idx_clinic_email_history_id"), ClinicEmailHistory.CLINIC_EMAIL_HISTORY, new OrderField[] { ClinicEmailHistory.CLINIC_EMAIL_HISTORY.ID }, false);
    public static final Index IDX_CLINIC_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_clinic_history_created_date"), ClinicHistory.CLINIC_HISTORY, new OrderField[] { ClinicHistory.CLINIC_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_CLINIC_HISTORY_ID = Internal.createIndex(DSL.name("idx_clinic_history_id"), ClinicHistory.CLINIC_HISTORY, new OrderField[] { ClinicHistory.CLINIC_HISTORY.ID }, false);
    public static final Index IDX_CLINIC_LOCATION_ACTIVE = Internal.createIndex(DSL.name("idx_clinic_location_active"), ClinicLocation.CLINIC_LOCATION, new OrderField[] { ClinicLocation.CLINIC_LOCATION.ACTIVE }, false);
    public static final Index IDX_CLINIC_LOCATION_CLINIC_ID = Internal.createIndex(DSL.name("idx_clinic_location_clinic_id"), ClinicLocation.CLINIC_LOCATION, new OrderField[] { ClinicLocation.CLINIC_LOCATION.CLINIC_ID }, false);
    public static final Index IDX_CLINIC_LOCATION_EMAIL_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_clinic_location_email_history_created_date"), ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY, new OrderField[] { ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_CLINIC_LOCATION_EMAIL_HISTORY_ID = Internal.createIndex(DSL.name("idx_clinic_location_email_history_id"), ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY, new OrderField[] { ClinicLocationEmailHistory.CLINIC_LOCATION_EMAIL_HISTORY.ID }, false);
    public static final Index IDX_CLINIC_LOCATION_EMAIL_LOCATION_ID = Internal.createIndex(DSL.name("idx_clinic_location_email_location_id"), ClinicLocationEmail.CLINIC_LOCATION_EMAIL, new OrderField[] { ClinicLocationEmail.CLINIC_LOCATION_EMAIL.CLINIC_LOCATION_ID }, false);
    public static final Index IDX_CLINIC_LOCATION_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_clinic_location_history_created_date"), ClinicLocationHistory.CLINIC_LOCATION_HISTORY, new OrderField[] { ClinicLocationHistory.CLINIC_LOCATION_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_CLINIC_LOCATION_HISTORY_ID = Internal.createIndex(DSL.name("idx_clinic_location_history_id"), ClinicLocationHistory.CLINIC_LOCATION_HISTORY, new OrderField[] { ClinicLocationHistory.CLINIC_LOCATION_HISTORY.ID }, false);
    public static final Index IDX_CLINIC_LOCATION_IS_PRIMARY = Internal.createIndex(DSL.name("idx_clinic_location_is_primary"), ClinicLocation.CLINIC_LOCATION, new OrderField[] { ClinicLocation.CLINIC_LOCATION.IS_PRIMARY }, false);
    public static final Index IDX_CLINIC_LOCATION_SUBURB = Internal.createIndex(DSL.name("idx_clinic_location_suburb"), ClinicLocation.CLINIC_LOCATION, new OrderField[] { ClinicLocation.CLINIC_LOCATION.SUBURB }, false);
    public static final Index IDX_CLINIC_NAME = Internal.createIndex(DSL.name("idx_clinic_name"), Clinic.CLINIC, new OrderField[] { Clinic.CLINIC.NAME }, false);
    public static final Index IDX_DOCTOR_ACTIVE = Internal.createIndex(DSL.name("idx_doctor_active"), Doctor.DOCTOR, new OrderField[] { Doctor.DOCTOR.ACTIVE }, false);
    public static final Index IDX_DOCTOR_CLINIC_ACTIVE = Internal.createIndex(DSL.name("idx_doctor_clinic_active"), DoctorClinic.DOCTOR_CLINIC, new OrderField[] { DoctorClinic.DOCTOR_CLINIC.ACTIVE }, false);
    public static final Index IDX_DOCTOR_CLINIC_CLINIC_ID = Internal.createIndex(DSL.name("idx_doctor_clinic_clinic_id"), DoctorClinic.DOCTOR_CLINIC, new OrderField[] { DoctorClinic.DOCTOR_CLINIC.CLINIC_ID }, false);
    public static final Index IDX_DOCTOR_CLINIC_DOCTOR_ID = Internal.createIndex(DSL.name("idx_doctor_clinic_doctor_id"), DoctorClinic.DOCTOR_CLINIC, new OrderField[] { DoctorClinic.DOCTOR_CLINIC.DOCTOR_ID }, false);
    public static final Index IDX_DOCTOR_CLINIC_HISTORY_ID = Internal.createIndex(DSL.name("idx_doctor_clinic_history_id"), DoctorClinicHistory.DOCTOR_CLINIC_HISTORY, new OrderField[] { DoctorClinicHistory.DOCTOR_CLINIC_HISTORY.ID }, false);
    public static final Index IDX_DOCTOR_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_doctor_history_created_date"), DoctorHistory.DOCTOR_HISTORY, new OrderField[] { DoctorHistory.DOCTOR_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_DOCTOR_HISTORY_ID = Internal.createIndex(DSL.name("idx_doctor_history_id"), DoctorHistory.DOCTOR_HISTORY, new OrderField[] { DoctorHistory.DOCTOR_HISTORY.ID }, false);
    public static final Index IDX_DOCTOR_LAST_NAME = Internal.createIndex(DSL.name("idx_doctor_last_name"), Doctor.DOCTOR, new OrderField[] { Doctor.DOCTOR.LAST_NAME }, false);
    public static final Index IDX_PASSWORD_RESET_TOKEN_USER_ID = Internal.createIndex(DSL.name("idx_password_reset_token_user_id"), PasswordResetToken.PASSWORD_RESET_TOKEN, new OrderField[] { PasswordResetToken.PASSWORD_RESET_TOKEN.USER_ID }, false);
    public static final Index IDX_PATIENT_CLINIC_CLINIC_ID = Internal.createIndex(DSL.name("idx_patient_clinic_clinic_id"), PatientClinic.PATIENT_CLINIC, new OrderField[] { PatientClinic.PATIENT_CLINIC.CLINIC_ID }, false);
    public static final Index IDX_PATIENT_CLINIC_CURRENT = Internal.createIndex(DSL.name("idx_patient_clinic_current"), PatientClinic.PATIENT_CLINIC, new OrderField[] { PatientClinic.PATIENT_CLINIC.IS_CURRENT }, false);
    public static final Index IDX_PATIENT_CLINIC_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_patient_clinic_history_created_date"), PatientClinicHistory.PATIENT_CLINIC_HISTORY, new OrderField[] { PatientClinicHistory.PATIENT_CLINIC_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_PATIENT_CLINIC_HISTORY_ID = Internal.createIndex(DSL.name("idx_patient_clinic_history_id"), PatientClinicHistory.PATIENT_CLINIC_HISTORY, new OrderField[] { PatientClinicHistory.PATIENT_CLINIC_HISTORY.ID }, false);
    public static final Index IDX_PATIENT_CLINIC_LOCATION_ID = Internal.createIndex(DSL.name("idx_patient_clinic_location_id"), PatientClinic.PATIENT_CLINIC, new OrderField[] { PatientClinic.PATIENT_CLINIC.CLINIC_LOCATION_ID }, false);
    public static final Index IDX_PATIENT_CLINIC_PATIENT_ID = Internal.createIndex(DSL.name("idx_patient_clinic_patient_id"), PatientClinic.PATIENT_CLINIC, new OrderField[] { PatientClinic.PATIENT_CLINIC.PATIENT_ID }, false);
    public static final Index IDX_PATIENT_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_patient_history_created_date"), PatientHistory.PATIENT_HISTORY, new OrderField[] { PatientHistory.PATIENT_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_PATIENT_HISTORY_ID = Internal.createIndex(DSL.name("idx_patient_history_id"), PatientHistory.PATIENT_HISTORY, new OrderField[] { PatientHistory.PATIENT_HISTORY.ID }, false);
    public static final Index IDX_PATIENT_LAST_NAME = Internal.createIndex(DSL.name("idx_patient_last_name"), Patient.PATIENT, new OrderField[] { Patient.PATIENT.LAST_NAME }, false);
    public static final Index IDX_PATIENT_STATUS = Internal.createIndex(DSL.name("idx_patient_status"), Patient.PATIENT, new OrderField[] { Patient.PATIENT.STATUS }, false);
    public static final Index IDX_REFRESH_TOKEN_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_refresh_token_history_created_date"), RefreshTokenHistory.REFRESH_TOKEN_HISTORY, new OrderField[] { RefreshTokenHistory.REFRESH_TOKEN_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_REFRESH_TOKEN_HISTORY_ID = Internal.createIndex(DSL.name("idx_refresh_token_history_id"), RefreshTokenHistory.REFRESH_TOKEN_HISTORY, new OrderField[] { RefreshTokenHistory.REFRESH_TOKEN_HISTORY.ID }, false);
    public static final Index IDX_REFRESH_TOKEN_TOKEN = Internal.createIndex(DSL.name("idx_refresh_token_token"), RefreshToken.REFRESH_TOKEN, new OrderField[] { RefreshToken.REFRESH_TOKEN.TOKEN }, false);
    public static final Index IDX_REFRESH_TOKEN_USER_ID = Internal.createIndex(DSL.name("idx_refresh_token_user_id"), RefreshToken.REFRESH_TOKEN, new OrderField[] { RefreshToken.REFRESH_TOKEN.USER_ID }, false);
    public static final Index IDX_REQUEST_CLINIC_ID = Internal.createIndex(DSL.name("idx_request_clinic_id"), Request.REQUEST, new OrderField[] { Request.REQUEST.CLINIC_ID }, false);
    public static final Index IDX_REQUEST_CLINIC_LOCATION_ID = Internal.createIndex(DSL.name("idx_request_clinic_location_id"), Request.REQUEST, new OrderField[] { Request.REQUEST.CLINIC_LOCATION_ID }, false);
    public static final Index IDX_REQUEST_DOCTOR_ID = Internal.createIndex(DSL.name("idx_request_doctor_id"), Request.REQUEST, new OrderField[] { Request.REQUEST.DOCTOR_ID }, false);
    public static final Index IDX_REQUEST_ENTERED_BY = Internal.createIndex(DSL.name("idx_request_entered_by"), Request.REQUEST, new OrderField[] { Request.REQUEST.ENTERED_BY }, false);
    public static final Index IDX_REQUEST_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_request_history_created_date"), RequestHistory.REQUEST_HISTORY, new OrderField[] { RequestHistory.REQUEST_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_REQUEST_HISTORY_ID = Internal.createIndex(DSL.name("idx_request_history_id"), RequestHistory.REQUEST_HISTORY, new OrderField[] { RequestHistory.REQUEST_HISTORY.ID }, false);
    public static final Index IDX_REQUEST_PATIENT_HISTORY_CREATED_DATE = Internal.createIndex(DSL.name("idx_request_patient_history_created_date"), RequestPatientHistory.REQUEST_PATIENT_HISTORY, new OrderField[] { RequestPatientHistory.REQUEST_PATIENT_HISTORY.HISTORY_CREATED_DATE }, false);
    public static final Index IDX_REQUEST_PATIENT_HISTORY_ID = Internal.createIndex(DSL.name("idx_request_patient_history_id"), RequestPatientHistory.REQUEST_PATIENT_HISTORY, new OrderField[] { RequestPatientHistory.REQUEST_PATIENT_HISTORY.ID }, false);
    public static final Index IDX_REQUEST_PATIENT_PATIENT_ID = Internal.createIndex(DSL.name("idx_request_patient_patient_id"), RequestPatient.REQUEST_PATIENT, new OrderField[] { RequestPatient.REQUEST_PATIENT.PATIENT_ID }, false);
    public static final Index IDX_REQUEST_PATIENT_REQUEST_ID = Internal.createIndex(DSL.name("idx_request_patient_request_id"), RequestPatient.REQUEST_PATIENT, new OrderField[] { RequestPatient.REQUEST_PATIENT.REQUEST_ID }, false);
    public static final Index IDX_REQUEST_RECEIVED_AT = Internal.createIndex(DSL.name("idx_request_received_at"), Request.REQUEST, new OrderField[] { Request.REQUEST.RECEIVED_AT }, false);
    public static final Index IDX_REQUEST_START_TIME = Internal.createIndex(DSL.name("idx_request_start_time"), Request.REQUEST, new OrderField[] { Request.REQUEST.START_TIME }, false);
    public static final Index IDX_REQUEST_STATUS = Internal.createIndex(DSL.name("idx_request_status"), Request.REQUEST, new OrderField[] { Request.REQUEST.STATUS }, false);
    public static final Index IDX_REQUEST_URGENCY = Internal.createIndex(DSL.name("idx_request_urgency"), Request.REQUEST, new OrderField[] { Request.REQUEST.URGENCY }, false);
}
