/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq;


import com.lifelinecalllog.jooq.tables.AppUser;
import com.lifelinecalllog.jooq.tables.AppUserHistory;
import com.lifelinecalllog.jooq.tables.Clinic;
import com.lifelinecalllog.jooq.tables.ClinicHistory;
import com.lifelinecalllog.jooq.tables.Doctor;
import com.lifelinecalllog.jooq.tables.DoctorHistory;
import com.lifelinecalllog.jooq.tables.Patient;
import com.lifelinecalllog.jooq.tables.PatientClinic;
import com.lifelinecalllog.jooq.tables.PatientClinicHistory;
import com.lifelinecalllog.jooq.tables.PatientHistory;
import com.lifelinecalllog.jooq.tables.RefreshToken;
import com.lifelinecalllog.jooq.tables.RefreshTokenHistory;
import com.lifelinecalllog.jooq.tables.Request;
import com.lifelinecalllog.jooq.tables.RequestHistory;
import com.lifelinecalllog.jooq.tables.RequestPatient;
import com.lifelinecalllog.jooq.tables.RequestPatientHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.app_user_history</code>.
     */
    public final AppUserHistory APP_USER_HISTORY = AppUserHistory.APP_USER_HISTORY;

    /**
     * The table <code>public.clinic</code>.
     */
    public final Clinic CLINIC = Clinic.CLINIC;

    /**
     * The table <code>public.clinic_history</code>.
     */
    public final ClinicHistory CLINIC_HISTORY = ClinicHistory.CLINIC_HISTORY;

    /**
     * The table <code>public.doctor</code>.
     */
    public final Doctor DOCTOR = Doctor.DOCTOR;

    /**
     * The table <code>public.doctor_history</code>.
     */
    public final DoctorHistory DOCTOR_HISTORY = DoctorHistory.DOCTOR_HISTORY;

    /**
     * The table <code>public.patient</code>.
     */
    public final Patient PATIENT = Patient.PATIENT;

    /**
     * The table <code>public.patient_clinic</code>.
     */
    public final PatientClinic PATIENT_CLINIC = PatientClinic.PATIENT_CLINIC;

    /**
     * The table <code>public.patient_clinic_history</code>.
     */
    public final PatientClinicHistory PATIENT_CLINIC_HISTORY = PatientClinicHistory.PATIENT_CLINIC_HISTORY;

    /**
     * The table <code>public.patient_history</code>.
     */
    public final PatientHistory PATIENT_HISTORY = PatientHistory.PATIENT_HISTORY;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;

    /**
     * The table <code>public.refresh_token_history</code>.
     */
    public final RefreshTokenHistory REFRESH_TOKEN_HISTORY = RefreshTokenHistory.REFRESH_TOKEN_HISTORY;

    /**
     * The table <code>public.request</code>.
     */
    public final Request REQUEST = Request.REQUEST;

    /**
     * The table <code>public.request_history</code>.
     */
    public final RequestHistory REQUEST_HISTORY = RequestHistory.REQUEST_HISTORY;

    /**
     * The table <code>public.request_patient</code>.
     */
    public final RequestPatient REQUEST_PATIENT = RequestPatient.REQUEST_PATIENT;

    /**
     * The table <code>public.request_patient_history</code>.
     */
    public final RequestPatientHistory REQUEST_PATIENT_HISTORY = RequestPatientHistory.REQUEST_PATIENT_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppUser.APP_USER,
            AppUserHistory.APP_USER_HISTORY,
            Clinic.CLINIC,
            ClinicHistory.CLINIC_HISTORY,
            Doctor.DOCTOR,
            DoctorHistory.DOCTOR_HISTORY,
            Patient.PATIENT,
            PatientClinic.PATIENT_CLINIC,
            PatientClinicHistory.PATIENT_CLINIC_HISTORY,
            PatientHistory.PATIENT_HISTORY,
            RefreshToken.REFRESH_TOKEN,
            RefreshTokenHistory.REFRESH_TOKEN_HISTORY,
            Request.REQUEST,
            RequestHistory.REQUEST_HISTORY,
            RequestPatient.REQUEST_PATIENT,
            RequestPatientHistory.REQUEST_PATIENT_HISTORY
        );
    }
}
