-- Add your history tables here following the pattern below
--
-- Example history table:
-- CREATE TABLE your_table_history (
--     -- Copy all columns from your main table
--     id UUID,
--     column1 VARCHAR(100),
--     column2 INTEGER,
--     ...
--     created_date TIMESTAMPTZ,
--     created_by VARCHAR(100),
--     last_modified_date TIMESTAMPTZ,
--     last_modified_by VARCHAR(100),
--     version INTEGER,
--     -- Additional history columns
--     dml_type VARCHAR(10) NOT NULL,
--     history_created_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
--
-- Example history trigger function:
-- CREATE OR REPLACE FUNCTION your_table_history_trigger_func()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     IF (TG_OP = 'DELETE') THEN
--         INSERT INTO your_table_history SELECT OLD.*, 'DELETE', CURRENT_TIMESTAMP;
--         RETURN OLD;
--     ELSIF (TG_OP = 'UPDATE') THEN
--         INSERT INTO your_table_history SELECT NEW.*, 'UPDATE', CURRENT_TIMESTAMP;
--         RETURN NEW;
--     ELSIF (TG_OP = 'INSERT') THEN
--         INSERT INTO your_table_history SELECT NEW.*, 'INSERT', CURRENT_TIMESTAMP;
--         RETURN NEW;
--     END IF;
--     RETURN NULL;
-- END;
-- $$ LANGUAGE plpgsql;
--
-- Example history trigger:
-- CREATE TRIGGER your_table_history_trigger
--     AFTER INSERT OR UPDATE OR DELETE ON your_table
--     FOR EACH ROW
--     EXECUTE FUNCTION your_table_history_trigger_func();
--
-- Example indexes:
-- CREATE INDEX idx_your_table_history_id ON your_table_history(id);
-- CREATE INDEX idx_your_table_history_created_date ON your_table_history(history_created_date);
