/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConfigurationHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private String configGroup;
    private Integer groupDisplayOrder;
    private String configKey;
    private String configDescription;
    private Integer configDisplayOrder;
    private String status;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;
    private String dmlType;
    private OffsetDateTime historyCreatedDate;

    public ConfigurationHistory() {}

    public ConfigurationHistory(ConfigurationHistory value) {
        this.configGroup = value.configGroup;
        this.groupDisplayOrder = value.groupDisplayOrder;
        this.configKey = value.configKey;
        this.configDescription = value.configDescription;
        this.configDisplayOrder = value.configDisplayOrder;
        this.status = value.status;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
        this.dmlType = value.dmlType;
        this.historyCreatedDate = value.historyCreatedDate;
    }

    public ConfigurationHistory(
        String configGroup,
        Integer groupDisplayOrder,
        String configKey,
        String configDescription,
        Integer configDisplayOrder,
        String status,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version,
        String dmlType,
        OffsetDateTime historyCreatedDate
    ) {
        this.configGroup = configGroup;
        this.groupDisplayOrder = groupDisplayOrder;
        this.configKey = configKey;
        this.configDescription = configDescription;
        this.configDisplayOrder = configDisplayOrder;
        this.status = status;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
        this.dmlType = dmlType;
        this.historyCreatedDate = historyCreatedDate;
    }

    /**
     * Getter for <code>public.configuration_history.config_group</code>.
     */
    public String getConfigGroup() {
        return this.configGroup;
    }

    /**
     * Setter for <code>public.configuration_history.config_group</code>.
     */
    public ConfigurationHistory setConfigGroup(String configGroup) {
        this.configGroup = configGroup;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.group_display_order</code>.
     */
    public Integer getGroupDisplayOrder() {
        return this.groupDisplayOrder;
    }

    /**
     * Setter for <code>public.configuration_history.group_display_order</code>.
     */
    public ConfigurationHistory setGroupDisplayOrder(Integer groupDisplayOrder) {
        this.groupDisplayOrder = groupDisplayOrder;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.config_key</code>.
     */
    public String getConfigKey() {
        return this.configKey;
    }

    /**
     * Setter for <code>public.configuration_history.config_key</code>.
     */
    public ConfigurationHistory setConfigKey(String configKey) {
        this.configKey = configKey;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.config_description</code>.
     */
    public String getConfigDescription() {
        return this.configDescription;
    }

    /**
     * Setter for <code>public.configuration_history.config_description</code>.
     */
    public ConfigurationHistory setConfigDescription(String configDescription) {
        this.configDescription = configDescription;
        return this;
    }

    /**
     * Getter for
     * <code>public.configuration_history.config_display_order</code>.
     */
    public Integer getConfigDisplayOrder() {
        return this.configDisplayOrder;
    }

    /**
     * Setter for
     * <code>public.configuration_history.config_display_order</code>.
     */
    public ConfigurationHistory setConfigDisplayOrder(Integer configDisplayOrder) {
        this.configDisplayOrder = configDisplayOrder;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.configuration_history.status</code>.
     */
    public ConfigurationHistory setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.configuration_history.created_date</code>.
     */
    public ConfigurationHistory setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.configuration_history.created_by</code>.
     */
    public ConfigurationHistory setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.configuration_history.last_modified_date</code>.
     */
    public ConfigurationHistory setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.configuration_history.last_modified_by</code>.
     */
    public ConfigurationHistory setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.configuration_history.version</code>.
     */
    public ConfigurationHistory setVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>public.configuration_history.dml_type</code>.
     */
    public String getDmlType() {
        return this.dmlType;
    }

    /**
     * Setter for <code>public.configuration_history.dml_type</code>.
     */
    public ConfigurationHistory setDmlType(String dmlType) {
        this.dmlType = dmlType;
        return this;
    }

    /**
     * Getter for
     * <code>public.configuration_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return this.historyCreatedDate;
    }

    /**
     * Setter for
     * <code>public.configuration_history.history_created_date</code>.
     */
    public ConfigurationHistory setHistoryCreatedDate(OffsetDateTime historyCreatedDate) {
        this.historyCreatedDate = historyCreatedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ConfigurationHistory other = (ConfigurationHistory) obj;
        if (this.configGroup == null) {
            if (other.configGroup != null)
                return false;
        }
        else if (!this.configGroup.equals(other.configGroup))
            return false;
        if (this.groupDisplayOrder == null) {
            if (other.groupDisplayOrder != null)
                return false;
        }
        else if (!this.groupDisplayOrder.equals(other.groupDisplayOrder))
            return false;
        if (this.configKey == null) {
            if (other.configKey != null)
                return false;
        }
        else if (!this.configKey.equals(other.configKey))
            return false;
        if (this.configDescription == null) {
            if (other.configDescription != null)
                return false;
        }
        else if (!this.configDescription.equals(other.configDescription))
            return false;
        if (this.configDisplayOrder == null) {
            if (other.configDisplayOrder != null)
                return false;
        }
        else if (!this.configDisplayOrder.equals(other.configDisplayOrder))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dmlType == null) {
            if (other.dmlType != null)
                return false;
        }
        else if (!this.dmlType.equals(other.dmlType))
            return false;
        if (this.historyCreatedDate == null) {
            if (other.historyCreatedDate != null)
                return false;
        }
        else if (!this.historyCreatedDate.equals(other.historyCreatedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.configGroup == null) ? 0 : this.configGroup.hashCode());
        result = prime * result + ((this.groupDisplayOrder == null) ? 0 : this.groupDisplayOrder.hashCode());
        result = prime * result + ((this.configKey == null) ? 0 : this.configKey.hashCode());
        result = prime * result + ((this.configDescription == null) ? 0 : this.configDescription.hashCode());
        result = prime * result + ((this.configDisplayOrder == null) ? 0 : this.configDisplayOrder.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dmlType == null) ? 0 : this.dmlType.hashCode());
        result = prime * result + ((this.historyCreatedDate == null) ? 0 : this.historyCreatedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConfigurationHistory (");

        sb.append(configGroup);
        sb.append(", ").append(groupDisplayOrder);
        sb.append(", ").append(configKey);
        sb.append(", ").append(configDescription);
        sb.append(", ").append(configDisplayOrder);
        sb.append(", ").append(status);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(dmlType);
        sb.append(", ").append(historyCreatedDate);

        sb.append(")");
        return sb.toString();
    }
}
