/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Doctor implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String firstName;
    private String lastName;
    private String providerNumber;
    private String phone;
    private String email;
    private Boolean active;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;

    public Doctor() {}

    public Doctor(Doctor value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.providerNumber = value.providerNumber;
        this.phone = value.phone;
        this.email = value.email;
        this.active = value.active;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
    }

    public Doctor(
        UUID id,
        String firstName,
        String lastName,
        String providerNumber,
        String phone,
        String email,
        Boolean active,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.providerNumber = providerNumber;
        this.phone = phone;
        this.email = email;
        this.active = active;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
    }

    /**
     * Getter for <code>public.doctor.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.doctor.id</code>.
     */
    public Doctor setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.doctor.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.doctor.first_name</code>.
     */
    public Doctor setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>public.doctor.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.doctor.last_name</code>.
     */
    public Doctor setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>public.doctor.provider_number</code>.
     */
    public String getProviderNumber() {
        return this.providerNumber;
    }

    /**
     * Setter for <code>public.doctor.provider_number</code>.
     */
    public Doctor setProviderNumber(String providerNumber) {
        this.providerNumber = providerNumber;
        return this;
    }

    /**
     * Getter for <code>public.doctor.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public.doctor.phone</code>.
     */
    public Doctor setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>public.doctor.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.doctor.email</code>.
     */
    public Doctor setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.doctor.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.doctor.active</code>.
     */
    public Doctor setActive(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>public.doctor.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.doctor.created_date</code>.
     */
    public Doctor setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.doctor.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.doctor.created_by</code>.
     */
    public Doctor setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.doctor.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.doctor.last_modified_date</code>.
     */
    public Doctor setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.doctor.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.doctor.last_modified_by</code>.
     */
    public Doctor setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.doctor.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.doctor.version</code>.
     */
    public Doctor setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Doctor other = (Doctor) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.providerNumber == null) {
            if (other.providerNumber != null)
                return false;
        }
        else if (!this.providerNumber.equals(other.providerNumber))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.providerNumber == null) ? 0 : this.providerNumber.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Doctor (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(providerNumber);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(active);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
