/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DoctorClinicHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID doctorId;
    private UUID clinicId;
    private UUID clinicLocationId;
    private Boolean active;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;
    private String dmlType;
    private OffsetDateTime historyCreatedDate;

    public DoctorClinicHistory() {}

    public DoctorClinicHistory(DoctorClinicHistory value) {
        this.id = value.id;
        this.doctorId = value.doctorId;
        this.clinicId = value.clinicId;
        this.clinicLocationId = value.clinicLocationId;
        this.active = value.active;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
        this.dmlType = value.dmlType;
        this.historyCreatedDate = value.historyCreatedDate;
    }

    public DoctorClinicHistory(
        UUID id,
        UUID doctorId,
        UUID clinicId,
        UUID clinicLocationId,
        Boolean active,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version,
        String dmlType,
        OffsetDateTime historyCreatedDate
    ) {
        this.id = id;
        this.doctorId = doctorId;
        this.clinicId = clinicId;
        this.clinicLocationId = clinicLocationId;
        this.active = active;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
        this.dmlType = dmlType;
        this.historyCreatedDate = historyCreatedDate;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.id</code>.
     */
    public DoctorClinicHistory setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.doctor_id</code>.
     */
    public UUID getDoctorId() {
        return this.doctorId;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.doctor_id</code>.
     */
    public DoctorClinicHistory setDoctorId(UUID doctorId) {
        this.doctorId = doctorId;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.clinic_id</code>.
     */
    public UUID getClinicId() {
        return this.clinicId;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.clinic_id</code>.
     */
    public DoctorClinicHistory setClinicId(UUID clinicId) {
        this.clinicId = clinicId;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.clinic_location_id</code>.
     */
    public UUID getClinicLocationId() {
        return this.clinicLocationId;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.clinic_location_id</code>.
     */
    public DoctorClinicHistory setClinicLocationId(UUID clinicLocationId) {
        this.clinicLocationId = clinicLocationId;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.active</code>.
     */
    public DoctorClinicHistory setActive(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.created_date</code>.
     */
    public DoctorClinicHistory setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.created_by</code>.
     */
    public DoctorClinicHistory setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.last_modified_date</code>.
     */
    public DoctorClinicHistory setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.last_modified_by</code>.
     */
    public DoctorClinicHistory setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.version</code>.
     */
    public DoctorClinicHistory setVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>public.doctor_clinic_history.dml_type</code>.
     */
    public String getDmlType() {
        return this.dmlType;
    }

    /**
     * Setter for <code>public.doctor_clinic_history.dml_type</code>.
     */
    public DoctorClinicHistory setDmlType(String dmlType) {
        this.dmlType = dmlType;
        return this;
    }

    /**
     * Getter for
     * <code>public.doctor_clinic_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return this.historyCreatedDate;
    }

    /**
     * Setter for
     * <code>public.doctor_clinic_history.history_created_date</code>.
     */
    public DoctorClinicHistory setHistoryCreatedDate(OffsetDateTime historyCreatedDate) {
        this.historyCreatedDate = historyCreatedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DoctorClinicHistory other = (DoctorClinicHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.doctorId == null) {
            if (other.doctorId != null)
                return false;
        }
        else if (!this.doctorId.equals(other.doctorId))
            return false;
        if (this.clinicId == null) {
            if (other.clinicId != null)
                return false;
        }
        else if (!this.clinicId.equals(other.clinicId))
            return false;
        if (this.clinicLocationId == null) {
            if (other.clinicLocationId != null)
                return false;
        }
        else if (!this.clinicLocationId.equals(other.clinicLocationId))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dmlType == null) {
            if (other.dmlType != null)
                return false;
        }
        else if (!this.dmlType.equals(other.dmlType))
            return false;
        if (this.historyCreatedDate == null) {
            if (other.historyCreatedDate != null)
                return false;
        }
        else if (!this.historyCreatedDate.equals(other.historyCreatedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.doctorId == null) ? 0 : this.doctorId.hashCode());
        result = prime * result + ((this.clinicId == null) ? 0 : this.clinicId.hashCode());
        result = prime * result + ((this.clinicLocationId == null) ? 0 : this.clinicLocationId.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dmlType == null) ? 0 : this.dmlType.hashCode());
        result = prime * result + ((this.historyCreatedDate == null) ? 0 : this.historyCreatedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DoctorClinicHistory (");

        sb.append(id);
        sb.append(", ").append(doctorId);
        sb.append(", ").append(clinicId);
        sb.append(", ").append(clinicLocationId);
        sb.append(", ").append(active);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(dmlType);
        sb.append(", ").append(historyCreatedDate);

        sb.append(")");
        return sb.toString();
    }
}
