/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordResetToken implements Serializable {

    private static final long serialVersionUID = 1L;

    private String token;
    private UUID userId;
    private OffsetDateTime expiresAt;
    private Boolean used;
    private OffsetDateTime createdAt;

    public PasswordResetToken() {}

    public PasswordResetToken(PasswordResetToken value) {
        this.token = value.token;
        this.userId = value.userId;
        this.expiresAt = value.expiresAt;
        this.used = value.used;
        this.createdAt = value.createdAt;
    }

    public PasswordResetToken(
        String token,
        UUID userId,
        OffsetDateTime expiresAt,
        Boolean used,
        OffsetDateTime createdAt
    ) {
        this.token = token;
        this.userId = userId;
        this.expiresAt = expiresAt;
        this.used = used;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.password_reset_token.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>public.password_reset_token.token</code>.
     */
    public PasswordResetToken setToken(String token) {
        this.token = token;
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.password_reset_token.user_id</code>.
     */
    public PasswordResetToken setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for <code>public.password_reset_token.expires_at</code>.
     */
    public PasswordResetToken setExpiresAt(OffsetDateTime expiresAt) {
        this.expiresAt = expiresAt;
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.used</code>.
     */
    public Boolean getUsed() {
        return this.used;
    }

    /**
     * Setter for <code>public.password_reset_token.used</code>.
     */
    public PasswordResetToken setUsed(Boolean used) {
        this.used = used;
        return this;
    }

    /**
     * Getter for <code>public.password_reset_token.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.password_reset_token.created_at</code>.
     */
    public PasswordResetToken setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PasswordResetToken other = (PasswordResetToken) obj;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.used == null) {
            if (other.used != null)
                return false;
        }
        else if (!this.used.equals(other.used))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.used == null) ? 0 : this.used.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PasswordResetToken (");

        sb.append(token);
        sb.append(", ").append(userId);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(used);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
