/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import com.lifelinecalllog.jooq.enums.PatientStatus;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PatientHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String firstName;
    private String lastName;
    private LocalDate dateOfBirth;
    private String phone;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;
    private String dmlType;
    private OffsetDateTime historyCreatedDate;
    private PatientStatus status;
    private String statusReason;
    private LocalDate deceasedDate;
    private String medicareNo;
    private String irnNo;
    private String remark;

    public PatientHistory() {}

    public PatientHistory(PatientHistory value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.dateOfBirth = value.dateOfBirth;
        this.phone = value.phone;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
        this.dmlType = value.dmlType;
        this.historyCreatedDate = value.historyCreatedDate;
        this.status = value.status;
        this.statusReason = value.statusReason;
        this.deceasedDate = value.deceasedDate;
        this.medicareNo = value.medicareNo;
        this.irnNo = value.irnNo;
        this.remark = value.remark;
    }

    public PatientHistory(
        UUID id,
        String firstName,
        String lastName,
        LocalDate dateOfBirth,
        String phone,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version,
        String dmlType,
        OffsetDateTime historyCreatedDate,
        PatientStatus status,
        String statusReason,
        LocalDate deceasedDate,
        String medicareNo,
        String irnNo,
        String remark
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.phone = phone;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
        this.dmlType = dmlType;
        this.historyCreatedDate = historyCreatedDate;
        this.status = status;
        this.statusReason = statusReason;
        this.deceasedDate = deceasedDate;
        this.medicareNo = medicareNo;
        this.irnNo = irnNo;
        this.remark = remark;
    }

    /**
     * Getter for <code>public.patient_history.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.patient_history.id</code>.
     */
    public PatientHistory setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.patient_history.first_name</code>.
     */
    public PatientHistory setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.patient_history.last_name</code>.
     */
    public PatientHistory setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return this.dateOfBirth;
    }

    /**
     * Setter for <code>public.patient_history.date_of_birth</code>.
     */
    public PatientHistory setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public.patient_history.phone</code>.
     */
    public PatientHistory setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.patient_history.created_date</code>.
     */
    public PatientHistory setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.patient_history.created_by</code>.
     */
    public PatientHistory setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.patient_history.last_modified_date</code>.
     */
    public PatientHistory setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.patient_history.last_modified_by</code>.
     */
    public PatientHistory setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.patient_history.version</code>.
     */
    public PatientHistory setVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.dml_type</code>.
     */
    public String getDmlType() {
        return this.dmlType;
    }

    /**
     * Setter for <code>public.patient_history.dml_type</code>.
     */
    public PatientHistory setDmlType(String dmlType) {
        this.dmlType = dmlType;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return this.historyCreatedDate;
    }

    /**
     * Setter for <code>public.patient_history.history_created_date</code>.
     */
    public PatientHistory setHistoryCreatedDate(OffsetDateTime historyCreatedDate) {
        this.historyCreatedDate = historyCreatedDate;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.status</code>.
     */
    public PatientStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.patient_history.status</code>.
     */
    public PatientHistory setStatus(PatientStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.status_reason</code>.
     */
    public String getStatusReason() {
        return this.statusReason;
    }

    /**
     * Setter for <code>public.patient_history.status_reason</code>.
     */
    public PatientHistory setStatusReason(String statusReason) {
        this.statusReason = statusReason;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.deceased_date</code>.
     */
    public LocalDate getDeceasedDate() {
        return this.deceasedDate;
    }

    /**
     * Setter for <code>public.patient_history.deceased_date</code>.
     */
    public PatientHistory setDeceasedDate(LocalDate deceasedDate) {
        this.deceasedDate = deceasedDate;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.medicare_no</code>.
     */
    public String getMedicareNo() {
        return this.medicareNo;
    }

    /**
     * Setter for <code>public.patient_history.medicare_no</code>.
     */
    public PatientHistory setMedicareNo(String medicareNo) {
        this.medicareNo = medicareNo;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.irn_no</code>.
     */
    public String getIrnNo() {
        return this.irnNo;
    }

    /**
     * Setter for <code>public.patient_history.irn_no</code>.
     */
    public PatientHistory setIrnNo(String irnNo) {
        this.irnNo = irnNo;
        return this;
    }

    /**
     * Getter for <code>public.patient_history.remark</code>.
     */
    public String getRemark() {
        return this.remark;
    }

    /**
     * Setter for <code>public.patient_history.remark</code>.
     */
    public PatientHistory setRemark(String remark) {
        this.remark = remark;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PatientHistory other = (PatientHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!this.firstName.equals(other.firstName))
            return false;
        if (this.lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!this.lastName.equals(other.lastName))
            return false;
        if (this.dateOfBirth == null) {
            if (other.dateOfBirth != null)
                return false;
        }
        else if (!this.dateOfBirth.equals(other.dateOfBirth))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dmlType == null) {
            if (other.dmlType != null)
                return false;
        }
        else if (!this.dmlType.equals(other.dmlType))
            return false;
        if (this.historyCreatedDate == null) {
            if (other.historyCreatedDate != null)
                return false;
        }
        else if (!this.historyCreatedDate.equals(other.historyCreatedDate))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.statusReason == null) {
            if (other.statusReason != null)
                return false;
        }
        else if (!this.statusReason.equals(other.statusReason))
            return false;
        if (this.deceasedDate == null) {
            if (other.deceasedDate != null)
                return false;
        }
        else if (!this.deceasedDate.equals(other.deceasedDate))
            return false;
        if (this.medicareNo == null) {
            if (other.medicareNo != null)
                return false;
        }
        else if (!this.medicareNo.equals(other.medicareNo))
            return false;
        if (this.irnNo == null) {
            if (other.irnNo != null)
                return false;
        }
        else if (!this.irnNo.equals(other.irnNo))
            return false;
        if (this.remark == null) {
            if (other.remark != null)
                return false;
        }
        else if (!this.remark.equals(other.remark))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.dateOfBirth == null) ? 0 : this.dateOfBirth.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dmlType == null) ? 0 : this.dmlType.hashCode());
        result = prime * result + ((this.historyCreatedDate == null) ? 0 : this.historyCreatedDate.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.statusReason == null) ? 0 : this.statusReason.hashCode());
        result = prime * result + ((this.deceasedDate == null) ? 0 : this.deceasedDate.hashCode());
        result = prime * result + ((this.medicareNo == null) ? 0 : this.medicareNo.hashCode());
        result = prime * result + ((this.irnNo == null) ? 0 : this.irnNo.hashCode());
        result = prime * result + ((this.remark == null) ? 0 : this.remark.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PatientHistory (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(dateOfBirth);
        sb.append(", ").append(phone);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(dmlType);
        sb.append(", ").append(historyCreatedDate);
        sb.append(", ").append(status);
        sb.append(", ").append(statusReason);
        sb.append(", ").append(deceasedDate);
        sb.append(", ").append(medicareNo);
        sb.append(", ").append(irnNo);
        sb.append(", ").append(remark);

        sb.append(")");
        return sb.toString();
    }
}
