/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokenHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String token;
    private UUID userId;
    private OffsetDateTime expiryDate;
    private Boolean revoked;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;
    private String dmlType;
    private OffsetDateTime historyCreatedDate;

    public RefreshTokenHistory() {}

    public RefreshTokenHistory(RefreshTokenHistory value) {
        this.id = value.id;
        this.token = value.token;
        this.userId = value.userId;
        this.expiryDate = value.expiryDate;
        this.revoked = value.revoked;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
        this.dmlType = value.dmlType;
        this.historyCreatedDate = value.historyCreatedDate;
    }

    public RefreshTokenHistory(
        UUID id,
        String token,
        UUID userId,
        OffsetDateTime expiryDate,
        Boolean revoked,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version,
        String dmlType,
        OffsetDateTime historyCreatedDate
    ) {
        this.id = id;
        this.token = token;
        this.userId = userId;
        this.expiryDate = expiryDate;
        this.revoked = revoked;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
        this.dmlType = dmlType;
        this.historyCreatedDate = historyCreatedDate;
    }

    /**
     * Getter for <code>public.refresh_token_history.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.refresh_token_history.id</code>.
     */
    public RefreshTokenHistory setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>public.refresh_token_history.token</code>.
     */
    public RefreshTokenHistory setToken(String token) {
        this.token = token;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.refresh_token_history.user_id</code>.
     */
    public RefreshTokenHistory setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.expiry_date</code>.
     */
    public OffsetDateTime getExpiryDate() {
        return this.expiryDate;
    }

    /**
     * Setter for <code>public.refresh_token_history.expiry_date</code>.
     */
    public RefreshTokenHistory setExpiryDate(OffsetDateTime expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.revoked</code>.
     */
    public Boolean getRevoked() {
        return this.revoked;
    }

    /**
     * Setter for <code>public.refresh_token_history.revoked</code>.
     */
    public RefreshTokenHistory setRevoked(Boolean revoked) {
        this.revoked = revoked;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.refresh_token_history.created_date</code>.
     */
    public RefreshTokenHistory setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.refresh_token_history.created_by</code>.
     */
    public RefreshTokenHistory setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.refresh_token_history.last_modified_date</code>.
     */
    public RefreshTokenHistory setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.refresh_token_history.last_modified_by</code>.
     */
    public RefreshTokenHistory setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.refresh_token_history.version</code>.
     */
    public RefreshTokenHistory setVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>public.refresh_token_history.dml_type</code>.
     */
    public String getDmlType() {
        return this.dmlType;
    }

    /**
     * Setter for <code>public.refresh_token_history.dml_type</code>.
     */
    public RefreshTokenHistory setDmlType(String dmlType) {
        this.dmlType = dmlType;
        return this;
    }

    /**
     * Getter for
     * <code>public.refresh_token_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return this.historyCreatedDate;
    }

    /**
     * Setter for
     * <code>public.refresh_token_history.history_created_date</code>.
     */
    public RefreshTokenHistory setHistoryCreatedDate(OffsetDateTime historyCreatedDate) {
        this.historyCreatedDate = historyCreatedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RefreshTokenHistory other = (RefreshTokenHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.expiryDate == null) {
            if (other.expiryDate != null)
                return false;
        }
        else if (!this.expiryDate.equals(other.expiryDate))
            return false;
        if (this.revoked == null) {
            if (other.revoked != null)
                return false;
        }
        else if (!this.revoked.equals(other.revoked))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dmlType == null) {
            if (other.dmlType != null)
                return false;
        }
        else if (!this.dmlType.equals(other.dmlType))
            return false;
        if (this.historyCreatedDate == null) {
            if (other.historyCreatedDate != null)
                return false;
        }
        else if (!this.historyCreatedDate.equals(other.historyCreatedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.expiryDate == null) ? 0 : this.expiryDate.hashCode());
        result = prime * result + ((this.revoked == null) ? 0 : this.revoked.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dmlType == null) ? 0 : this.dmlType.hashCode());
        result = prime * result + ((this.historyCreatedDate == null) ? 0 : this.historyCreatedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshTokenHistory (");

        sb.append(id);
        sb.append(", ").append(token);
        sb.append(", ").append(userId);
        sb.append(", ").append(expiryDate);
        sb.append(", ").append(revoked);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(dmlType);
        sb.append(", ").append(historyCreatedDate);

        sb.append(")");
        return sb.toString();
    }
}
