/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RequestPatientHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID requestId;
    private UUID patientId;
    private String notes;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;
    private String dmlType;
    private OffsetDateTime historyCreatedDate;

    public RequestPatientHistory() {}

    public RequestPatientHistory(RequestPatientHistory value) {
        this.id = value.id;
        this.requestId = value.requestId;
        this.patientId = value.patientId;
        this.notes = value.notes;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
        this.dmlType = value.dmlType;
        this.historyCreatedDate = value.historyCreatedDate;
    }

    public RequestPatientHistory(
        UUID id,
        UUID requestId,
        UUID patientId,
        String notes,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version,
        String dmlType,
        OffsetDateTime historyCreatedDate
    ) {
        this.id = id;
        this.requestId = requestId;
        this.patientId = patientId;
        this.notes = notes;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
        this.dmlType = dmlType;
        this.historyCreatedDate = historyCreatedDate;
    }

    /**
     * Getter for <code>public.request_patient_history.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.request_patient_history.id</code>.
     */
    public RequestPatientHistory setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.request_id</code>.
     */
    public UUID getRequestId() {
        return this.requestId;
    }

    /**
     * Setter for <code>public.request_patient_history.request_id</code>.
     */
    public RequestPatientHistory setRequestId(UUID requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.patient_id</code>.
     */
    public UUID getPatientId() {
        return this.patientId;
    }

    /**
     * Setter for <code>public.request_patient_history.patient_id</code>.
     */
    public RequestPatientHistory setPatientId(UUID patientId) {
        this.patientId = patientId;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.notes</code>.
     */
    public String getNotes() {
        return this.notes;
    }

    /**
     * Setter for <code>public.request_patient_history.notes</code>.
     */
    public RequestPatientHistory setNotes(String notes) {
        this.notes = notes;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.request_patient_history.created_date</code>.
     */
    public RequestPatientHistory setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.request_patient_history.created_by</code>.
     */
    public RequestPatientHistory setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for
     * <code>public.request_patient_history.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for
     * <code>public.request_patient_history.last_modified_date</code>.
     */
    public RequestPatientHistory setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.request_patient_history.last_modified_by</code>.
     */
    public RequestPatientHistory setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.request_patient_history.version</code>.
     */
    public RequestPatientHistory setVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>public.request_patient_history.dml_type</code>.
     */
    public String getDmlType() {
        return this.dmlType;
    }

    /**
     * Setter for <code>public.request_patient_history.dml_type</code>.
     */
    public RequestPatientHistory setDmlType(String dmlType) {
        this.dmlType = dmlType;
        return this;
    }

    /**
     * Getter for
     * <code>public.request_patient_history.history_created_date</code>.
     */
    public OffsetDateTime getHistoryCreatedDate() {
        return this.historyCreatedDate;
    }

    /**
     * Setter for
     * <code>public.request_patient_history.history_created_date</code>.
     */
    public RequestPatientHistory setHistoryCreatedDate(OffsetDateTime historyCreatedDate) {
        this.historyCreatedDate = historyCreatedDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RequestPatientHistory other = (RequestPatientHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.requestId == null) {
            if (other.requestId != null)
                return false;
        }
        else if (!this.requestId.equals(other.requestId))
            return false;
        if (this.patientId == null) {
            if (other.patientId != null)
                return false;
        }
        else if (!this.patientId.equals(other.patientId))
            return false;
        if (this.notes == null) {
            if (other.notes != null)
                return false;
        }
        else if (!this.notes.equals(other.notes))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.dmlType == null) {
            if (other.dmlType != null)
                return false;
        }
        else if (!this.dmlType.equals(other.dmlType))
            return false;
        if (this.historyCreatedDate == null) {
            if (other.historyCreatedDate != null)
                return false;
        }
        else if (!this.historyCreatedDate.equals(other.historyCreatedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.requestId == null) ? 0 : this.requestId.hashCode());
        result = prime * result + ((this.patientId == null) ? 0 : this.patientId.hashCode());
        result = prime * result + ((this.notes == null) ? 0 : this.notes.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.dmlType == null) ? 0 : this.dmlType.hashCode());
        result = prime * result + ((this.historyCreatedDate == null) ? 0 : this.historyCreatedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RequestPatientHistory (");

        sb.append(id);
        sb.append(", ").append(requestId);
        sb.append(", ").append(patientId);
        sb.append(", ").append(notes);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(dmlType);
        sb.append(", ").append(historyCreatedDate);

        sb.append(")");
        return sb.toString();
    }
}
