/*
 * This file is generated by jOOQ.
 */
package com.lifelinecalllog.jooq.tables.pojos;


import com.lifelinecalllog.jooq.enums.RequestStatus;
import com.lifelinecalllog.jooq.enums.Urgency;
import com.lifelinecalllog.jooq.enums.VisitType;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Request implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID clinicId;
    private UUID doctorId;
    private VisitType visitType;
    private Urgency urgency;
    private RequestStatus status;
    private String requestDetails;
    private OffsetDateTime receivedAt;
    private OffsetDateTime createdDate;
    private UUID createdBy;
    private OffsetDateTime lastModifiedDate;
    private UUID lastModifiedBy;
    private Integer version;
    private OffsetDateTime startTime;
    private OffsetDateTime endTime;

    public Request() {}

    public Request(Request value) {
        this.id = value.id;
        this.clinicId = value.clinicId;
        this.doctorId = value.doctorId;
        this.visitType = value.visitType;
        this.urgency = value.urgency;
        this.status = value.status;
        this.requestDetails = value.requestDetails;
        this.receivedAt = value.receivedAt;
        this.createdDate = value.createdDate;
        this.createdBy = value.createdBy;
        this.lastModifiedDate = value.lastModifiedDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.version = value.version;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
    }

    public Request(
        UUID id,
        UUID clinicId,
        UUID doctorId,
        VisitType visitType,
        Urgency urgency,
        RequestStatus status,
        String requestDetails,
        OffsetDateTime receivedAt,
        OffsetDateTime createdDate,
        UUID createdBy,
        OffsetDateTime lastModifiedDate,
        UUID lastModifiedBy,
        Integer version,
        OffsetDateTime startTime,
        OffsetDateTime endTime
    ) {
        this.id = id;
        this.clinicId = clinicId;
        this.doctorId = doctorId;
        this.visitType = visitType;
        this.urgency = urgency;
        this.status = status;
        this.requestDetails = requestDetails;
        this.receivedAt = receivedAt;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.version = version;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * Getter for <code>public.request.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.request.id</code>.
     */
    public Request setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.request.clinic_id</code>.
     */
    public UUID getClinicId() {
        return this.clinicId;
    }

    /**
     * Setter for <code>public.request.clinic_id</code>.
     */
    public Request setClinicId(UUID clinicId) {
        this.clinicId = clinicId;
        return this;
    }

    /**
     * Getter for <code>public.request.doctor_id</code>.
     */
    public UUID getDoctorId() {
        return this.doctorId;
    }

    /**
     * Setter for <code>public.request.doctor_id</code>.
     */
    public Request setDoctorId(UUID doctorId) {
        this.doctorId = doctorId;
        return this;
    }

    /**
     * Getter for <code>public.request.visit_type</code>.
     */
    public VisitType getVisitType() {
        return this.visitType;
    }

    /**
     * Setter for <code>public.request.visit_type</code>.
     */
    public Request setVisitType(VisitType visitType) {
        this.visitType = visitType;
        return this;
    }

    /**
     * Getter for <code>public.request.urgency</code>.
     */
    public Urgency getUrgency() {
        return this.urgency;
    }

    /**
     * Setter for <code>public.request.urgency</code>.
     */
    public Request setUrgency(Urgency urgency) {
        this.urgency = urgency;
        return this;
    }

    /**
     * Getter for <code>public.request.status</code>.
     */
    public RequestStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.request.status</code>.
     */
    public Request setStatus(RequestStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.request.request_details</code>.
     */
    public String getRequestDetails() {
        return this.requestDetails;
    }

    /**
     * Setter for <code>public.request.request_details</code>.
     */
    public Request setRequestDetails(String requestDetails) {
        this.requestDetails = requestDetails;
        return this;
    }

    /**
     * Getter for <code>public.request.received_at</code>.
     */
    public OffsetDateTime getReceivedAt() {
        return this.receivedAt;
    }

    /**
     * Setter for <code>public.request.received_at</code>.
     */
    public Request setReceivedAt(OffsetDateTime receivedAt) {
        this.receivedAt = receivedAt;
        return this;
    }

    /**
     * Getter for <code>public.request.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.request.created_date</code>.
     */
    public Request setCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Getter for <code>public.request.created_by</code>.
     */
    public UUID getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.request.created_by</code>.
     */
    public Request setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>public.request.last_modified_date</code>.
     */
    public OffsetDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>public.request.last_modified_date</code>.
     */
    public Request setLastModifiedDate(OffsetDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Getter for <code>public.request.last_modified_by</code>.
     */
    public UUID getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>public.request.last_modified_by</code>.
     */
    public Request setLastModifiedBy(UUID lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>public.request.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.request.version</code>.
     */
    public Request setVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>public.request.start_time</code>.
     */
    public OffsetDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Setter for <code>public.request.start_time</code>.
     */
    public Request setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Getter for <code>public.request.end_time</code>.
     */
    public OffsetDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Setter for <code>public.request.end_time</code>.
     */
    public Request setEndTime(OffsetDateTime endTime) {
        this.endTime = endTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Request other = (Request) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.clinicId == null) {
            if (other.clinicId != null)
                return false;
        }
        else if (!this.clinicId.equals(other.clinicId))
            return false;
        if (this.doctorId == null) {
            if (other.doctorId != null)
                return false;
        }
        else if (!this.doctorId.equals(other.doctorId))
            return false;
        if (this.visitType == null) {
            if (other.visitType != null)
                return false;
        }
        else if (!this.visitType.equals(other.visitType))
            return false;
        if (this.urgency == null) {
            if (other.urgency != null)
                return false;
        }
        else if (!this.urgency.equals(other.urgency))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.requestDetails == null) {
            if (other.requestDetails != null)
                return false;
        }
        else if (!this.requestDetails.equals(other.requestDetails))
            return false;
        if (this.receivedAt == null) {
            if (other.receivedAt != null)
                return false;
        }
        else if (!this.receivedAt.equals(other.receivedAt))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!this.startTime.equals(other.startTime))
            return false;
        if (this.endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!this.endTime.equals(other.endTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.clinicId == null) ? 0 : this.clinicId.hashCode());
        result = prime * result + ((this.doctorId == null) ? 0 : this.doctorId.hashCode());
        result = prime * result + ((this.visitType == null) ? 0 : this.visitType.hashCode());
        result = prime * result + ((this.urgency == null) ? 0 : this.urgency.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.requestDetails == null) ? 0 : this.requestDetails.hashCode());
        result = prime * result + ((this.receivedAt == null) ? 0 : this.receivedAt.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Request (");

        sb.append(id);
        sb.append(", ").append(clinicId);
        sb.append(", ").append(doctorId);
        sb.append(", ").append(visitType);
        sb.append(", ").append(urgency);
        sb.append(", ").append(status);
        sb.append(", ").append(requestDetails);
        sb.append(", ").append(receivedAt);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(version);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);

        sb.append(")");
        return sb.toString();
    }
}
